import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, rmSync, writeFileSync, unlinkSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { generate, type SchemaInput } from "../src/emit.ts";
import { OUT_OF_SCOPE, run } from "../src/main.ts";
import { SchemaError } from "../src/field.ts";

const SCHEMAS = new URL("../../../../refs/schemas/", import.meta.url);

function tiny(overrides: Partial<SchemaInput["schema"]> = {}): SchemaInput {
  return {
    family: "quadro",
    source: "refs/schemas/quadro_commands.json",
    schema: {
      commands: {
        set_volume: {
          report_id: "0x70",
          params: [
            { name: "id", type: "ubyte" },
            { name: "density", type: "byte", bit_width: 3, default: 2 },
            { name: "slots", type: '{"elem_type": "ubyte * 2", "count": 2}', size: 4 },
            { name: "blob", type: "ubyte * 4", size: 4 },
          ],
        },
        get_levels: {
          report_id: "0x70",
          params: [],
          returns: [
            { name: "level", type: "uint16" },
            { name: "peaks", type: "ubyte * 2", size: 2 },
            { name: "pairs", type: '{"fields": [["a", "ubyte", 4], ["b", "byte", 4]], "count": 2}', size: 2 },
          ],
        },
      },
      cyclic_reports: {
        "0x73": { report_id: "0x73", fields: [{ name: "current_preset", type: "ubyte", bit_width: 3 }, { name: "meters", type: "ubyte * 3", size: 3 }] },
      },
      ...overrides,
    },
  };
}

test("commands become typed params and returns, sorted by name", () => {
  const code = generate([tiny()]).get("quadro.ts");
  assert.ok(code, "quadro.ts is generated");
  assert.ok(code.startsWith("// Generated by tools/gen-types from refs/schemas/quadro_commands.json. Do not edit."), code.slice(0, 120));
  assert.ok(code.indexOf("get_levels:") < code.indexOf("set_volume:"), "commands are sorted");
  assert.match(code, /export interface QuadroCommands \{/);
  // Scalars are numbers with width and range; defaults make a param optional.
  assert.match(code, /\/\*\* u8, 0\.\.255 \*\/\s*id: number;/);
  assert.match(code, /\/\*\* i8, 3 bits, -4\.\.3; default 2 \*\/\s*density\?: number;/);
  // Byte-carrying params accept bytes; element arrays also accept one entry per element.
  assert.match(code, /blob: Bytes;/);
  assert.match(code, /slots: Bytes \| readonly Bytes\[\];/);
  // Outputs follow the server: numbers, byte arrays as Uint8Array, struct arrays as object arrays.
  assert.match(code, /level: number;/);
  assert.match(code, /peaks: Uint8Array;/);
  assert.match(code, /pairs: Array<\{/);
  assert.match(code, /\/\*\* i8, 4 bits, -8\.\.7 \*\/\s*b: number;/);
  assert.match(code, /set_volume: \{\s*params: \{[\s\S]*?\};\s*returns: null;/);
});

test("cyclic reports are typed by their server report id", () => {
  const code = generate([tiny()]).get("quadro.ts") ?? "";
  assert.match(code, /export interface QuadroCyclicReports \{\s*"0x73": \{/);
  assert.match(code, /\/\*\* u8, 3 bits, 0\.\.7 \*\/\s*current_preset: number;/);
  assert.match(code, /meters: Uint8Array;/);
});

test("doc comments use singular units for one", () => {
  const code = generate([tiny({ cyclic_reports: { "0x73": { fields: [{ name: "flag", type: "ubyte", bit_width: 1 }, { name: "pairs", type: '{"fields": [["a", "ubyte", 4], ["b", "byte", 4]], "count": 2}' }] } } })]).get("quadro.ts") ?? "";
  assert.match(code, /\/\*\* u8, 1 bit, 0\.\.1 \*\/\s*flag: number;/);
  assert.match(code, /\/\*\* 2 × struct of 1 byte \*\/\s*pairs:/);
});

test("runtime descriptors carry every parsed field for the client and the cross-check", () => {
  const code = generate([tiny()]).get("quadro.ts") ?? "";
  assert.match(code, /export const quadroSchema = \{/);
  assert.match(code, /"set_volume": \{ "reportId": "0x70", "params": \[\{ "kind": "scalar", "name": "id", "scalar": "u8" \}/);
  assert.match(code, /\} as const satisfies FamilySchema;/);
});

test("the index maps each family to its command and cyclic types", () => {
  const index = generate([tiny(), { ...tiny(), family: "studio", source: "refs/schemas/studio_commands.json" }]).get("index.ts") ?? "";
  assert.match(index, /export type Family = "quadro" \| "studio";/);
  assert.match(index, /quadro: \{ commands: QuadroCommands; cyclic: QuadroCyclicReports \};/);
  assert.match(index, /export const schemas = \{ quadro: quadroSchema, studio: studioSchema \} as const;/);
});

test("zero-length arrays are generated with a warning, not omitted", () => {
  const schema = tiny({ commands: { set_x: { report_id: "0x70", params: [{ name: "data", type: "ubyte * 0", size: 0 }] } } });
  assert.match(generate([schema]).get("quadro.ts") ?? "", /zero-length array; the extractor could not resolve its count/);
});

test("an unrecognised type fails generation, naming the command", () => {
  const schema = tiny({ commands: { set_x: { report_id: "0x70", params: [{ name: "gain", type: "float" }] } } });
  assert.throws(() => generate([schema]), (e: unknown) => e instanceof SchemaError && e.message.includes("set_x.params.gain"));
});

test("topology is emitted as a typed constant, indexed by family, and checked", () => {
  const topology = {
    family: "quadro",
    source: { tool: "refs/tools/scripts/extract_topology.py", bytecode: "3.8", blobs: [] },
    inputs: [{ id: "PREAMP0", type: "PREAMP", typeId: 8, name: "PREAMP", channels: 4, color: "#25a844" }],
    outputs: [],
    signalPresent: [],
    availableChannels: [],
    mixers: { count: 4, channels: 32, command: "set_mixer", masterChannel: 0, stereoLinkId: 3, inputGroups: [], outputGroups: [] },
    assumptions: ["group ids follow the controller"],
  };
  const files = generate([{ ...tiny(), topology }]);
  assert.match(files.get("quadro.ts") ?? "", /export const quadroTopology = \{ "family": "quadro", "source": /);
  assert.match(files.get("quadro.ts") ?? "", /"typeId": 8, "name": "PREAMP", "channels": 4, "color": "#25a844" \}\][\s\S]*\} as const satisfies Topology;/);
  assert.match(files.get("index.ts") ?? "", /import \{ quadroSchema, quadroTopology, type QuadroCommands/);
  assert.match(files.get("index.ts") ?? "", /export const topologies = \{ quadro: quadroTopology \} as const;/);
  assert.doesNotMatch(generate([tiny()]).get("index.ts") ?? "", /topologies/, "no topology, no index entry");

  const bad = (change: object) => () => generate([{ ...tiny(), topology: { ...topology, ...change } }]);
  assert.throws(bad({ family: "studio" }), (e: unknown) => e instanceof SchemaError && e.message.includes('quadro topology: names family "studio"'));
  assert.throws(bad({ mixers: { count: 4 } }), /mixers needs count, channels and command/);
  assert.throws(bad({ inputs: "none" }), /inputs must be a list/);
});

test("the real schemas generate deterministically", () => {
  const inputs = ["quadro", "studio"].map((family) => ({
    family,
    source: `refs/schemas/${family}_commands.json`,
    schema: JSON.parse(readFileSync(new URL(`${family}_commands.json`, SCHEMAS), "utf8")),
    topology: JSON.parse(readFileSync(new URL(`${family}_topology.json`, SCHEMAS), "utf8")) as unknown,
  }));
  const first = generate(inputs);
  assert.deepEqual([...first.keys()].sort(), ["index.ts", "quadro.ts", "studio.ts"]);
  assert.deepEqual(generate(inputs), first);
});

test("licence management is left out of the generated types, as the server leaves it out", () => {
  const out = mkdtempSync(join(tmpdir(), "gen-types-"));
  try {
    const schemasDir = new URL(SCHEMAS).pathname.replace(/^\/([A-Za-z]:)/, "$1");
    run({ schemasDir, outDir: out, check: false });
    for (const family of ["quadro", "studio"]) {
      const code = readFileSync(join(out, `${family}.ts`), "utf8");
      for (const name of OUT_OF_SCOPE) assert.equal(code.includes(name), false, `${family}.ts has ${name}`);
    }
    assert.match(readFileSync(join(out, "quadro.ts"), "utf8"), /get_feature_mask/, "the feature mask is still read");
  } finally {
    rmSync(out, { recursive: true, force: true });
  }
});

test("--check passes on fresh output and fails on a changed or missing file", () => {
  const out = mkdtempSync(join(tmpdir(), "gen-types-"));
  try {
    const schemasDir = new URL(SCHEMAS).pathname.replace(/^\/([A-Za-z]:)/, "$1");
    assert.deepEqual(run({ schemasDir, outDir: out, check: false }), { ok: true, changed: ["index.ts", "quadro.ts", "studio.ts"] });
    assert.deepEqual(run({ schemasDir, outDir: out, check: true }), { ok: true, changed: [] });

    writeFileSync(join(out, "studio.ts"), readFileSync(join(out, "studio.ts"), "utf8") + "\n// hand edit\n");
    unlinkSync(join(out, "index.ts"));
    assert.deepEqual(run({ schemasDir, outDir: out, check: true }), { ok: false, changed: ["index.ts", "studio.ts"] });
    assert.equal(readFileSync(join(out, "studio.ts"), "utf8").includes("hand edit"), true, "--check writes nothing");
  } finally {
    rmSync(out, { recursive: true, force: true });
  }
});
