// Generated by refs/tools/scripts/mic_emulations.py from the Quadro panel's own model classes.
// Do not edit by hand: re-run the script against an extracted PYZ instead.
//
// Each Antelope microphone has its own catalogue, and the indexes are per target: Berlin 47 FT is
// 2 on the Edge Solo and 1 on the Edge Duo. Index 0 is the microphone itself, unemulated.

/** `target` in `set_mic_emulation`: which Antelope microphone is on the preamp. */
export const MIC_TARGETS = {
  ANY: 0,
  EDGE_DUO: 1,
  VERGE: 2,
  EDGE_SOLO: 3,
  EDGE_QUADRO: 4,
  ACCORD: 5,
  EDGE_NOTE: 6,
} as const;

/** `emu_model` by target: the microphones each one can be made to sound like. */
export const MIC_EMULATIONS: Readonly<Record<number, readonly string[]>> = {
  // MicTarget.EDGE_DUO
  1: [
    "Edge Duo",
    "Berlin 47 FT",
    "Berlin 87",
    "Berlin 67",
    "Berlin M103",
    "Tokyo 800T",
    "Oxford 4038",
    "Berlin 49T",
    "Berlin 57",
    "Vienna 12",
    "Sacramento 121R",
    "Vienna 414",
    "Berlin V563",
    "Minnesota 20",
    "Illinois 7B",
    "Berlin K86",
    "Berlin/Halske M25",
    "Berlin 47TU",
    "Berlin M251",
  ],
  // MicTarget.VERGE
  2: [
    "Verge",
    "Berlin 184",
    "Perth 55",
    "Freiburg 6",
    "Aalborg 4006",
    "Hamburg 40",
    "Berlin K86",
    "Berlin K53",
    "Berlin K54",
    "Illinois 57",
    "Illinois 7B",
    "Hamburg 211",
    "Hamburg 441",
    "Vienna 112",
  ],
  // MicTarget.EDGE_SOLO
  3: [
    "Edge Solo",
    "Tokyo 800T",
    "Berlin 47 FT",
    "Berlin 67",
    "Berlin 87",
    "Berlin M103",
    "Berlin 49T",
    "Berlin 57",
    "Vienna 12",
    "Vienna 414",
    "Berlin V563",
    "Illinois 57",
    "Illinois 7B",
    "Minnesota 20",
    "Vienna 112",
    "Berlin K86",
    "Berlin 47TU",
    "Berlin M251",
    "Hamburg 441",
  ],
  // MicTarget.EDGE_QUADRO
  4: [
    "Edge Quadro",
    "Berlin 47 FT",
    "Berlin 87",
    "Berlin 67",
    "Berlin M103",
    "Tokyo 800T",
    "Oxford 4038",
    "Berlin 49T",
    "Berlin 57",
    "Vienna 12",
    "Sacramento 121R",
    "Vienna 414",
    "Berlin K86",
    "Berlin 47TU",
    "Berlin V563",
    "Berlin/Halske M25",
    "Berlin M251",
    "Minnesota 20",
    "Illinois 7B",
  ],
  // MicTarget.ACCORD
  5: [
    "Accord",
    "Tokyo 800T",
    "Berlin 47 FT",
    "Berlin 67",
    "Berlin 87",
    "Berlin M103",
    "Berlin 49T",
    "Berlin 57",
    "Vienna 12",
    "Vienna 414",
    "Berlin V563",
    "Illinois 57",
    "Illinois 7B",
    "Minnesota 20",
    "Vienna 112",
    "Berlin K86",
    "Berlin 47TU",
    "Berlin M251",
    "Hamburg 441",
  ],
  // MicTarget.EDGE_NOTE
  6: [
    "Edge Note",
    "Berlin 184",
    "Perth 55",
    "Freiburg 6",
    "Aalborg 4006",
    "Hamburg 40",
    "Berlin K86",
    "Berlin K53",
    "Berlin K54",
    "Illinois 57",
    "Illinois 7B",
    "Hamburg 211",
    "Hamburg 441",
    "Vienna 112",
  ],
};

/**
 * A model's polar pattern. `pattern` runs from `min` to `max` and means an angle from `minAngle` to
 * `maxAngle`: +1 omni, 0 cardioid, -1 figure-8 (`MicModelBaseWithPAngle`). A model whose `min` and
 * `max` are equal has a fixed pattern. A microphone missing from this table has no polar pattern at
 * all. Only the Edge Duo, Edge Quadro and Accord models carry one.
 */
export interface PatternRange {
  min: number;
  max: number;
  initial: number;
  minAngle: number;
  maxAngle: number;
}

export const MIC_PATTERNS: Readonly<Record<number, Readonly<Record<number, PatternRange>>>> = {
  // MicTarget.EDGE_DUO
  1: {
    0: { min: 0, max: 100, initial: 50, minAngle: 1, maxAngle: -1 },
    1: { min: 0, max: 0, initial: 0, minAngle: 0, maxAngle: 0 },
    2: { min: 0, max: 2, initial: 1, minAngle: 1, maxAngle: -1 },
    3: { min: 0, max: 2, initial: 1, minAngle: 1, maxAngle: -1 },
    4: { min: 0, max: 0, initial: 0, minAngle: 0, maxAngle: 0 },
    5: { min: 0, max: 1, initial: 1, minAngle: 1, maxAngle: 0 },
    6: { min: 0, max: 0, initial: 0, minAngle: -1, maxAngle: -1 },
    7: { min: 0, max: 2, initial: 1, minAngle: 1, maxAngle: -1 },
    8: { min: 0, max: 8, initial: 4, minAngle: 1, maxAngle: -1 },
    9: { min: 0, max: 8, initial: 4, minAngle: 1, maxAngle: -1 },
    10: { min: 0, max: 0, initial: 0, minAngle: -1, maxAngle: -1 },
    11: { min: 0, max: 8, initial: 4, minAngle: 1, maxAngle: -1 },
    12: { min: 0, max: 0, initial: 0, minAngle: 0, maxAngle: 0 },
    13: { min: 0, max: 0, initial: 0, minAngle: 0, maxAngle: 0 },
    14: { min: 0, max: 0, initial: 0, minAngle: 0, maxAngle: 0 },
    15: { min: 0, max: 1, initial: 1, minAngle: 1, maxAngle: 0 },
    16: { min: 0, max: 0, initial: 0, minAngle: 0, maxAngle: 0 },
    17: { min: 0, max: 1, initial: 1, minAngle: 1, maxAngle: 0 },
    18: { min: 0, max: 1, initial: 1, minAngle: 1, maxAngle: 0 },
  },
  // MicTarget.EDGE_QUADRO
  4: {
    0: { min: 0, max: 100, initial: 50, minAngle: 1, maxAngle: -1 },
    1: { min: 0, max: 0, initial: 0, minAngle: 0, maxAngle: 0 },
    2: { min: 0, max: 2, initial: 1, minAngle: 1, maxAngle: -1 },
    3: { min: 0, max: 2, initial: 1, minAngle: 1, maxAngle: -1 },
    4: { min: 0, max: 0, initial: 0, minAngle: 0, maxAngle: 0 },
    5: { min: 0, max: 1, initial: 1, minAngle: 1, maxAngle: 0 },
    6: { min: 0, max: 0, initial: 0, minAngle: -1, maxAngle: -1 },
    7: { min: 0, max: 2, initial: 1, minAngle: 1, maxAngle: -1 },
    8: { min: 0, max: 8, initial: 4, minAngle: 1, maxAngle: -1 },
    9: { min: 0, max: 8, initial: 4, minAngle: 1, maxAngle: -1 },
    10: { min: 0, max: 0, initial: 0, minAngle: -1, maxAngle: -1 },
    11: { min: 0, max: 8, initial: 4, minAngle: 1, maxAngle: -1 },
    12: { min: 0, max: 1, initial: 1, minAngle: 1, maxAngle: 0 },
    13: { min: 0, max: 1, initial: 1, minAngle: 1, maxAngle: 0 },
    14: { min: 0, max: 0, initial: 0, minAngle: 0, maxAngle: 0 },
    15: { min: 0, max: 0, initial: 0, minAngle: 0, maxAngle: 0 },
    16: { min: 0, max: 1, initial: 1, minAngle: 1, maxAngle: 0 },
    17: { min: 0, max: 0, initial: 0, minAngle: 0, maxAngle: 0 },
    18: { min: 0, max: 0, initial: 0, minAngle: 0, maxAngle: 0 },
  },
  // MicTarget.ACCORD
  5: {
    0: { min: 0, max: 100, initial: 50, minAngle: 1, maxAngle: -1 },
    1: { min: 0, max: 1, initial: 1, minAngle: 1, maxAngle: 0 },
    2: { min: 0, max: 0, initial: 0, minAngle: 0, maxAngle: 0 },
    3: { min: 0, max: 2, initial: 1, minAngle: 1, maxAngle: -1 },
    4: { min: 0, max: 2, initial: 1, minAngle: 1, maxAngle: -1 },
    5: { min: 0, max: 0, initial: 0, minAngle: 0, maxAngle: 0 },
    6: { min: 0, max: 2, initial: 1, minAngle: 1, maxAngle: -1 },
    7: { min: 0, max: 100, initial: 50, minAngle: 1, maxAngle: -1 },
    8: { min: 0, max: 8, initial: 4, minAngle: 1, maxAngle: -1 },
    9: { min: 0, max: 8, initial: 4, minAngle: 1, maxAngle: -1 },
    10: { min: 0, max: 100, initial: 50, minAngle: 1, maxAngle: -1 },
    11: { min: 0, max: 100, initial: 50, minAngle: 1, maxAngle: -1 },
    12: { min: 0, max: 100, initial: 50, minAngle: 1, maxAngle: -1 },
    13: { min: 0, max: 100, initial: 50, minAngle: 1, maxAngle: -1 },
    14: { min: 0, max: 100, initial: 50, minAngle: 1, maxAngle: -1 },
    15: { min: 0, max: 100, initial: 50, minAngle: 1, maxAngle: -1 },
    16: { min: 0, max: 100, initial: 50, minAngle: 1, maxAngle: -1 },
    17: { min: 0, max: 100, initial: 50, minAngle: 1, maxAngle: -1 },
    18: { min: 0, max: 100, initial: 50, minAngle: 1, maxAngle: -1 },
  },
};

/**
 * Where each emulation's licence sits in `get_feature_mask`, by target and then `emu_model`: a bit
 * counted from the reply's second byte, least significant bit first (the panel's
 * `parse_feature_mask`). Index 0, the microphone itself, is the microphone's own feature, which the
 * panel also uses to grey the microphone out of its list; each emulation has a feature of its own.
 */
export const MIC_LICENCE_BITS: Readonly<Record<number, readonly number[]>> = {
  // MicTarget.EDGE_DUO
  1: [
    408, // mic_emu_edge
    410, // mic_emu_model_edge_berlin47fet
    411, // mic_emu_model_edge_berlin87
    412, // mic_emu_model_edge_berlin67
    413, // mic_emu_model_edge_berlinm103
    414, // mic_emu_model_edge_tokyo800t
    448, // mic_emu_model_edge_oxford4038
    449, // mic_emu_model_edge_berlin49t
    450, // mic_emu_model_edge_berlin57
    451, // mic_emu_model_edge_vienna12
    452, // mic_emu_model_edge_sacramento121r
    453, // mic_emu_model_edge_vienna414
    554, // mic_emu_model_edge_berlinv563
    555, // mic_emu_model_edge_minnesota20
    556, // mic_emu_model_edge_illinois7b
    557, // mic_emu_model_edge_berlink86
    558, // mic_emu_model_edge_berlinm25
    559, // mic_emu_model_edge_berlin47tu
    560, // mic_emu_model_edge_berlinm251
  ],
  // MicTarget.VERGE
  2: [
    409, // mic_emu_verge
    415, // mic_emu_model_verge_berlin184
    416, // mic_emu_model_verge_perth55
    417, // mic_emu_model_verge_freiburg6
    418, // mic_emu_model_verge_aalborg4006
    419, // mic_emu_model_verge_hamburg40
    546, // mic_emu_model_verge_berlink86
    547, // mic_emu_model_verge_berlink53
    548, // mic_emu_model_verge_berlink54
    549, // mic_emu_model_verge_illinois57
    550, // mic_emu_model_verge_illinois7b
    551, // mic_emu_model_verge_hamburg211
    552, // mic_emu_model_verge_hamburg441
    553, // mic_emu_model_verge_vienna112
  ],
  // MicTarget.EDGE_SOLO
  3: [
    499, // mic_emu_edge_solo
    500, // mic_emu_model_edge_solo_tokyo800t
    501, // mic_emu_model_edge_solo_berlin47fet
    502, // mic_emu_model_edge_solo_berlin67
    503, // mic_emu_model_edge_solo_berlin87
    504, // mic_emu_model_edge_solo_berlinm103
    505, // mic_emu_model_edge_solo_berlin49t
    506, // mic_emu_model_edge_solo_berlin57
    507, // mic_emu_model_edge_solo_vienna12
    508, // mic_emu_model_edge_solo_vienna414
    509, // mic_emu_model_edge_solo_berlinv563
    510, // mic_emu_model_edge_solo_illinois57
    511, // mic_emu_model_edge_solo_illinois7b
    512, // mic_emu_model_edge_solo_minnesota20
    513, // mic_emu_model_edge_solo_vienna112
    514, // mic_emu_model_edge_solo_berlink86
    515, // mic_emu_model_edge_solo_berlin47tu
    516, // mic_emu_model_edge_solo_berlinm251
    517, // mic_emu_model_edge_solo_hamburg441
  ],
  // MicTarget.EDGE_QUADRO
  4: [
    527, // mic_emu_edge_quadro
    528, // mic_emu_model_edge_quadro_berlin47fet
    529, // mic_emu_model_edge_quadro_berlin87
    530, // mic_emu_model_edge_quadro_berlin67
    531, // mic_emu_model_edge_quadro_berlinm103
    532, // mic_emu_model_edge_quadro_tokyo800t
    533, // mic_emu_model_edge_quadro_oxford4038
    534, // mic_emu_model_edge_quadro_berlin49t
    535, // mic_emu_model_edge_quadro_berlin57
    536, // mic_emu_model_edge_quadro_vienna12
    537, // mic_emu_model_edge_quadro_sacramento121r
    538, // mic_emu_model_edge_quadro_vienna414
    539, // mic_emu_model_edge_quadro_berlink86
    540, // mic_emu_model_edge_quadro_berlin47tu
    541, // mic_emu_model_edge_quadro_berlinv563
    542, // mic_emu_model_edge_quadro_berlinm25
    543, // mic_emu_model_edge_quadro_berlinm251
    544, // mic_emu_model_edge_quadro_minnesota20
    545, // mic_emu_model_edge_quadro_illinois7b
  ],
  // MicTarget.ACCORD
  5: [
    805, // mic_emu_accord
    806, // mic_emu_model_accord_tokyo800t
    807, // mic_emu_model_accord_berlin47fet
    808, // mic_emu_model_accord_berlin67
    809, // mic_emu_model_accord_berlin87
    810, // mic_emu_model_accord_berlinm103
    811, // mic_emu_model_accord_berlin49t
    812, // mic_emu_model_accord_berlin57
    813, // mic_emu_model_accord_vienna12
    814, // mic_emu_model_accord_vienna414
    815, // mic_emu_model_accord_berlinv563
    888, // mic_emu_model_accord_illinois57
    889, // mic_emu_model_accord_illinois7b
    890, // mic_emu_model_accord_minnesota20
    891, // mic_emu_model_accord_vienna112
    892, // mic_emu_model_accord_berlink86
    893, // mic_emu_model_accord_berlin47tu
    894, // mic_emu_model_accord_berlinm251
    895, // mic_emu_model_accord_hamburg441
  ],
  // MicTarget.EDGE_NOTE
  6: [
    996, // mic_emu_edge_note
    997, // mic_emu_model_edge_note_berlin184
    998, // mic_emu_model_edge_note_perth55
    999, // mic_emu_model_edge_note_freiburg6
    1000, // mic_emu_model_edge_note_aalborg4006
    1001, // mic_emu_model_edge_note_hamburg40
    1002, // mic_emu_model_edge_note_berlink86
    1003, // mic_emu_model_edge_note_berlink53
    1004, // mic_emu_model_edge_note_berlink54
    1005, // mic_emu_model_edge_note_illinois57
    1006, // mic_emu_model_edge_note_illinois7b
    1007, // mic_emu_model_edge_note_hamburg211
    1008, // mic_emu_model_edge_note_hamburg441
    1009, // mic_emu_model_edge_note_vienna112
  ],
};
