// Generated by refs/tools/scripts/mic_emulations.py from the Quadro panel's own model classes.
// Do not edit by hand: re-run the script against an extracted PYZ instead.
//
// Each Antelope microphone has its own catalogue, and the indexes are per target — Berlin 47 FT is
// 2 on the Edge Solo and 1 on the Edge Duo. Index 0 is the microphone itself, unemulated.

/** `target` in `set_mic_emulation`: which Antelope microphone is on the preamp. */
export const MIC_TARGETS = {
  ANY: 0,
  EDGE_DUO: 1,
  VERGE: 2,
  EDGE_SOLO: 3,
  EDGE_QUADRO: 4,
  ACCORD: 5,
  EDGE_NOTE: 6,
} as const;

/** `emu_model` by target: the microphones each one can be made to sound like. */
export const MIC_EMULATIONS: Readonly<Record<number, readonly string[]>> = {
  // MicTarget.EDGE_DUO
  1: [
    "Edge Duo",
    "Berlin 47 FT",
    "Berlin 87",
    "Berlin 67",
    "Berlin M103",
    "Tokyo 800T",
    "Oxford 4038",
    "Berlin 49T",
    "Berlin 57",
    "Vienna 12",
    "Sacramento 121R",
    "Vienna 414",
    "Berlin V563",
    "Minnesota 20",
    "Illinois 7B",
    "Berlin K86",
    "Berlin/Halske M25",
    "Berlin 47TU",
    "Berlin M251",
  ],
  // MicTarget.VERGE
  2: [
    "Verge",
    "Berlin 184",
    "Perth 55",
    "Freiburg 6",
    "Aalborg 4006",
    "Hamburg 40",
    "Berlin K86",
    "Berlin K53",
    "Berlin K54",
    "Illinois 57",
    "Illinois 7B",
    "Hamburg 211",
    "Hamburg 441",
    "Vienna 112",
  ],
  // MicTarget.EDGE_SOLO
  3: [
    "Edge Solo",
    "Tokyo 800T",
    "Berlin 47 FT",
    "Berlin 67",
    "Berlin 87",
    "Berlin M103",
    "Berlin 49T",
    "Berlin 57",
    "Vienna 12",
    "Vienna 414",
    "Berlin V563",
    "Illinois 57",
    "Illinois 7B",
    "Minnesota 20",
    "Vienna 112",
    "Berlin K86",
    "Berlin 47TU",
    "Berlin M251",
    "Hamburg 441",
  ],
  // MicTarget.EDGE_QUADRO
  4: [
    "Edge Quadro",
    "Berlin 47 FT",
    "Berlin 87",
    "Berlin 67",
    "Berlin M103",
    "Tokyo 800T",
    "Oxford 4038",
    "Berlin 49T",
    "Berlin 57",
    "Vienna 12",
    "Sacramento 121R",
    "Vienna 414",
    "Berlin K86",
    "Berlin 47TU",
    "Berlin V563",
    "Berlin/Halske M25",
    "Berlin M251",
    "Minnesota 20",
    "Illinois 7B",
  ],
  // MicTarget.ACCORD
  5: [
    "Accord",
    "Tokyo 800T",
    "Berlin 47 FT",
    "Berlin 67",
    "Berlin 87",
    "Berlin M103",
    "Berlin 49T",
    "Berlin 57",
    "Vienna 12",
    "Vienna 414",
    "Berlin V563",
    "Illinois 57",
    "Illinois 7B",
    "Minnesota 20",
    "Vienna 112",
    "Berlin K86",
    "Berlin 47TU",
    "Berlin M251",
    "Hamburg 441",
  ],
  // MicTarget.EDGE_NOTE
  6: [
    "Edge Note",
    "Berlin 184",
    "Perth 55",
    "Freiburg 6",
    "Aalborg 4006",
    "Hamburg 40",
    "Berlin K86",
    "Berlin K53",
    "Berlin K54",
    "Illinois 57",
    "Illinois 7B",
    "Hamburg 211",
    "Hamburg 441",
    "Vienna 112",
  ],
};

/**
 * A model's polar pattern. `pattern` runs from `min` to `max` and means an angle from `minAngle` to
 * `maxAngle`: +1 omni, 0 cardioid, -1 figure-8 (`MicModelBaseWithPAngle`). A model whose `min` and
 * `max` are equal has a fixed pattern. A microphone missing from this table has no polar pattern at
 * all — only the Edge Duo, Edge Quadro and Accord models carry one.
 */
export interface PatternRange {
  min: number;
  max: number;
  initial: number;
  minAngle: number;
  maxAngle: number;
}

export const MIC_PATTERNS: Readonly<Record<number, Readonly<Record<number, PatternRange>>>> = {
  // MicTarget.EDGE_DUO
  1: {
    0: { min: 0, max: 100, initial: 50, minAngle: 1, maxAngle: -1 },
    1: { min: 0, max: 0, initial: 0, minAngle: 0, maxAngle: 0 },
    2: { min: 0, max: 2, initial: 1, minAngle: 1, maxAngle: -1 },
    3: { min: 0, max: 2, initial: 1, minAngle: 1, maxAngle: -1 },
    4: { min: 0, max: 0, initial: 0, minAngle: 0, maxAngle: 0 },
    5: { min: 0, max: 1, initial: 1, minAngle: 1, maxAngle: 0 },
    6: { min: 0, max: 0, initial: 0, minAngle: -1, maxAngle: -1 },
    7: { min: 0, max: 2, initial: 1, minAngle: 1, maxAngle: -1 },
    8: { min: 0, max: 8, initial: 4, minAngle: 1, maxAngle: -1 },
    9: { min: 0, max: 8, initial: 4, minAngle: 1, maxAngle: -1 },
    10: { min: 0, max: 0, initial: 0, minAngle: -1, maxAngle: -1 },
    11: { min: 0, max: 8, initial: 4, minAngle: 1, maxAngle: -1 },
    12: { min: 0, max: 0, initial: 0, minAngle: 0, maxAngle: 0 },
    13: { min: 0, max: 0, initial: 0, minAngle: 0, maxAngle: 0 },
    14: { min: 0, max: 0, initial: 0, minAngle: 0, maxAngle: 0 },
    15: { min: 0, max: 1, initial: 1, minAngle: 1, maxAngle: 0 },
    16: { min: 0, max: 0, initial: 0, minAngle: 0, maxAngle: 0 },
    17: { min: 0, max: 1, initial: 1, minAngle: 1, maxAngle: 0 },
    18: { min: 0, max: 1, initial: 1, minAngle: 1, maxAngle: 0 },
  },
  // MicTarget.EDGE_QUADRO
  4: {
    0: { min: 0, max: 100, initial: 50, minAngle: 1, maxAngle: -1 },
    1: { min: 0, max: 0, initial: 0, minAngle: 0, maxAngle: 0 },
    2: { min: 0, max: 2, initial: 1, minAngle: 1, maxAngle: -1 },
    3: { min: 0, max: 2, initial: 1, minAngle: 1, maxAngle: -1 },
    4: { min: 0, max: 0, initial: 0, minAngle: 0, maxAngle: 0 },
    5: { min: 0, max: 1, initial: 1, minAngle: 1, maxAngle: 0 },
    6: { min: 0, max: 0, initial: 0, minAngle: -1, maxAngle: -1 },
    7: { min: 0, max: 2, initial: 1, minAngle: 1, maxAngle: -1 },
    8: { min: 0, max: 8, initial: 4, minAngle: 1, maxAngle: -1 },
    9: { min: 0, max: 8, initial: 4, minAngle: 1, maxAngle: -1 },
    10: { min: 0, max: 0, initial: 0, minAngle: -1, maxAngle: -1 },
    11: { min: 0, max: 8, initial: 4, minAngle: 1, maxAngle: -1 },
    12: { min: 0, max: 1, initial: 1, minAngle: 1, maxAngle: 0 },
    13: { min: 0, max: 1, initial: 1, minAngle: 1, maxAngle: 0 },
    14: { min: 0, max: 0, initial: 0, minAngle: 0, maxAngle: 0 },
    15: { min: 0, max: 0, initial: 0, minAngle: 0, maxAngle: 0 },
    16: { min: 0, max: 1, initial: 1, minAngle: 1, maxAngle: 0 },
    17: { min: 0, max: 0, initial: 0, minAngle: 0, maxAngle: 0 },
    18: { min: 0, max: 0, initial: 0, minAngle: 0, maxAngle: 0 },
  },
  // MicTarget.ACCORD
  5: {
    0: { min: 0, max: 100, initial: 50, minAngle: 1, maxAngle: -1 },
    1: { min: 0, max: 1, initial: 1, minAngle: 1, maxAngle: 0 },
    2: { min: 0, max: 0, initial: 0, minAngle: 0, maxAngle: 0 },
    3: { min: 0, max: 2, initial: 1, minAngle: 1, maxAngle: -1 },
    4: { min: 0, max: 2, initial: 1, minAngle: 1, maxAngle: -1 },
    5: { min: 0, max: 0, initial: 0, minAngle: 0, maxAngle: 0 },
    6: { min: 0, max: 2, initial: 1, minAngle: 1, maxAngle: -1 },
    7: { min: 0, max: 100, initial: 50, minAngle: 1, maxAngle: -1 },
    8: { min: 0, max: 8, initial: 4, minAngle: 1, maxAngle: -1 },
    9: { min: 0, max: 8, initial: 4, minAngle: 1, maxAngle: -1 },
    10: { min: 0, max: 100, initial: 50, minAngle: 1, maxAngle: -1 },
    11: { min: 0, max: 100, initial: 50, minAngle: 1, maxAngle: -1 },
    12: { min: 0, max: 100, initial: 50, minAngle: 1, maxAngle: -1 },
    13: { min: 0, max: 100, initial: 50, minAngle: 1, maxAngle: -1 },
    14: { min: 0, max: 100, initial: 50, minAngle: 1, maxAngle: -1 },
    15: { min: 0, max: 100, initial: 50, minAngle: 1, maxAngle: -1 },
    16: { min: 0, max: 100, initial: 50, minAngle: 1, maxAngle: -1 },
    17: { min: 0, max: 100, initial: 50, minAngle: 1, maxAngle: -1 },
    18: { min: 0, max: 100, initial: 50, minAngle: 1, maxAngle: -1 },
  },
};
