// The explain mode's text: one entry per key an element carries in `data-explain`. A chunk of its own,
// fetched the first time the mode is turned on (`explain.ts`), so the app does not carry it for
// everyone who never does. Nothing else may import it statically; `test/bundle-split.test.ts` checks.
//
// Written from the app's code and the decision log. Where what a control does on the hardware has not
// been measured, an entry says what the app knows and stops there. `{name}` is the element's own
// name for the thing ("Preamp 3", "HP1", "Vox"), or the entry's `name` when it gives none.
//
// Keys are whole literals in the elements, never put together from parts, so `test/explain.test.ts`
// can find every one; `e2e/explain-coverage.spec.ts` walks every page and fails on a control with no
// key, or a key with no entry here.

import type { Catalogue } from "./explain-rules.ts";

/** Keys with an entry that nothing in the elements uses yet, for a section being built elsewhere. */
export const RESERVED_KEYS: readonly string[] = [];

const STEP_KEYS = "Arrow keys and the wheel move it a step at a time, Page Up and Page Down in bigger steps, and a double-click puts it back to its starting value.";
const LEVEL_KEYS = "Arrow keys and the wheel move it a step at a time, Page Up and Page Down in bigger steps. A double-click sets -20 dB, or 0 dB when the header's Double-click menu says unity; Ctrl or Cmd and a click always sets 0 dB.";
const NOTHING_SENT = "Nothing is sent to a device.";
const WORKSPACE = "It is kept in the workspace on the server, so everyone using this server sees the same.";

export const CATALOGUE: Catalogue = {
  // The header.
  "header.explain": {
    title: "Explain mode",
    what: "Turns these explanations on and off. While it is on, pointing at or focusing anything shows what it is, what changing it does and what to watch for.",
    effect: "Remembered in this browser only. It changes nothing on a device.",
  },
  "header.explain-tap": {
    title: "Explain by tapping",
    what: "For a screen with no hover. While it is lit, a tap or click on a control explains it instead of using it.",
    effect: "Tap it again, or press Escape, to use the controls again.",
    watch: "While it is lit, taps do nothing but explain, so a button will not press and a slider will not move.",
  },
  "header.page.devices": { title: "Devices page", what: "One device's identity, name, clock, settings, test oscillator, presets and power." },
  "header.page.workspace": { title: "Workspace page", what: "What this server keeps for everyone: device names and colours, surfaces, digital cables, groups, snapshots, and backup." },
  "header.page.inputs": { title: "Inputs page", what: "Every hardware input on the device: preamp type, gain, 48V and phase, digital input gains, and on the Quadro, mic emulation." },
  "header.page.outputs": { title: "Outputs page", what: "Every hardware output's volume, mute and (Quadro) dim, the output trims, and on the Studio+, talkback." },
  "header.page.mixer": { title: "Mixer page", what: "The device's four hardware mixes, as channels you set up, each with its fader, pan, mute and solo in the mix you pick." },
  "header.page.routing": { title: "Routing page", what: "Which source feeds every destination on the device, as the vendor panel's routing tab lays it out." },
  "header.page.effects": { title: "Effects page", what: "The device's effect chains and its reverb: what is loaded, bypass, each effect's settings, and the reverb's sends and returns." },
  "header.page.aggregate": { title: "Aggregate page", what: "One audio driver a DAW opens with two or more interfaces underneath it: whether this PC can run it, registering it, what is in it, and how it is holding while a DAW plays." },
  "header.version": {
    title: "Version",
    what: "Which version of Gazelle this server is running. It is the number to quote when something goes wrong or an update is being talked about.",
    effect: "Shown only while the explain mode is on. The tray menu names the same version at the top.",
  },
  "header.update": {
    title: "Update",
    what: "Shown only when the updater wants something: a version downloaded and ready, one that has not been fetched because this install asked not to, or a check or download that failed.",
    effect: "Ready asks twice, as every large action here does, and then restarts the server into the new version: the devices are let go and picked up again, and this page reconnects by itself. The other two ask once and simply fetch or try again.",
  },
  "header.update-note": {
    title: "Update in progress",
    what: "A version being downloaded and checked. Nothing has been replaced yet, and the app keeps running while it happens.",
    effect: "Nothing to press. It becomes a Restart button when the download is verified and in place.",
  },
  "header.backend": {
    title: "Backend",
    what: "What this server is driving: usb is the real interfaces over USB; loopback is the built in emulator, which touches no hardware.",
    watch: "On usb every control acts on the device you are listening through.",
  },
  "header.dry-run": {
    title: "Dry run",
    what: "The server was started in dry run: every command reports the bytes it would send, and nothing is written to a device.",
    effect: "Controls still move, so you can see what they would do. Reads answer nothing, so values start at defaults.",
  },
  "header.connection": {
    title: "Connection",
    what: "Whether this page is connected to the server. While it is not, every control is disabled until it reconnects.",
  },
  "header.theme": { title: "Theme", what: "The colours the app is drawn in. Remembered in this browser only." },
  "header.double-click": {
    title: "Double-click on a level",
    what: "What a double-click does to a level: its safe level (-20 dB on a fader, -30 dB on a volume, off on a reverb send), or unity. Ctrl or Cmd and a click always sets unity.",
    effect: "Remembered in this browser only. The wheel does not step this menu, and a phone does not show it, having no double-click.",
  },

  // The shell.
  "app.menu": { title: "Sidebar", what: "Opens the sidebar over the page: device cards, the output meters and the Control Room. Escape or a tap outside closes it." },
  "app.disconnected": { title: "Not connected", what: "The server is not answering. Controls stay disabled until the page reconnects, which it tries on its own." },
  "app.page-retry": { title: "Try again", what: "Reloads the app, since a browser will not fetch a page's code again in the same document after it failed once." },
  "sidebar.move": { title: "Move the sidebar", what: "Docks the sidebar on the other side of the page. Remembered in this browser." },
  "sidebar.fold": { title: "Fold the sidebar", what: "Folds the sidebar to a narrow rail, or opens it again. Remembered in this browser." },
  "sidebar.close": { title: "Close the sidebar", what: "Closes the sidebar drawer and hands focus back to the menu button." },
  "sidebar.devices": { title: "Devices", what: "A card per connected device. Picking one switches the page you are on to that device." },
  "sidebar.meter": { title: "Meter", what: "The output levels of the device on screen, with a clip light per output and how soon clip lights clear themselves." },
  "sidebar.control-room": { title: "Control Room", what: "The outputs you chose on the Outputs page, each with volume, mute, dim (Quadro) and mono, and on the Studio+, talkback." },

  // Device cards.
  "devicelist.card": {
    title: "{name}",
    name: "Device",
    what: "A connected device, by the name you gave it. Its state at a glance comes from its status report.",
    effect: "Picking it switches the page you are on to this device. On the Workspace page it selects the device without leaving.",
  },
  "devicelist.unknown": { title: "Unknown model", what: "The server does not know this device's model, so only its Devices page can show it and nothing it reports can be decoded." },
  "devicelist.input": {
    title: "Input activity",
    what: "Lit when any hardware input has signal above -60 dBFS, and red when one clips, held for 1.5 s so a short clip is still seen.",
    effect: "Covers the preamps, S/PDIF and ADAT, and on the Studio+ the line inputs.",
  },
  "devicelist.clock": { title: "Clock", what: "The sample rate the device measures (or the rate it is set to, before one is measured), and whether it is locked to its clock source." },
  "devicelist.lock": { title: "Lock", what: "LOCKED when the device reports itself locked to its clock source, NO LOCK when it does not." },
  "devicelist.state": { title: "Power and preset", what: "Whether the device is on or in standby, and which of its five presets it is on." },

  // The Meter section.
  "meter.output": {
    title: "{name} meter",
    name: "Output",
    what: "The level leaving {name}, left and right, in dB below full scale, from 0 down to -60.",
    effect: "The bar rises fast and falls back steadily. The bright marker holds the loudest recent level for 1.5 s, then falls. The figure is that held peak.",
  },
  "meter.output-clip": {
    title: "{name} clip light",
    name: "Output",
    what: "Lights when either side of {name} reaches full scale.",
    effect: "Click it to clear it. It also clears by itself after the time chosen above, counted from when the clip ends.",
  },
  "meter.auto-clear": { title: "Clip lights clear after", what: "How long after a clip ends every clip light clears itself, on the strips too. Hold keeps them lit until cleared.", effect: "Remembered in this browser." },
  "meter.clear-all": { title: "Clear all clip lights", what: "Clears every clip light on every device: outputs, strips and effects." },
  "meter.none": {
    title: "No output meters",
    what: "The Studio+ reports its output levels only through a meter bank that can be pointed at different sources. The app does not point it, since that is a write to the device a page would make on its own.",
  },

  // The Control Room.
  "cr.device": { title: "Control Room device", what: "The device the Control Room shows: the one on the page you are on, or the one last selected." },
  "cr.volume": {
    title: "{name} volume",
    name: "Output",
    what: "The hardware volume of {name}, in dB of attenuation: 0 dB at the right, down to off at the left.",
    effect: "Sends the new volume straight to the device, the same control as the Outputs page's. A double-click sets -30 dB, or 0 dB when the header's Double-click menu says unity; Ctrl or Cmd and a click always sets 0 dB.",
    watch: "This is the volume of what you are listening to: a drag to the right is as loud as the output goes.",
  },
  "cr.mute": { title: "{name} mute", name: "Output", what: "Mutes {name} on the device. Its volume is kept and comes back when unmuted." },
  "cr.dim": {
    title: "{name} dim",
    name: "Output",
    what: "Dims {name}: the Quadro lowers the output by its own dim amount while this is lit.",
    watch: "How many dB the device dims by is its own; the app has not measured it.",
  },
  "cr.mono": {
    title: "{name} mono",
    name: "Output",
    what: "Neither model can make an output mono, so this sums the mix that feeds {name} to mono: every channel in that mix is panned to centre, and the mix lowered by what summing gains on that device so the level stays about the same. Both are put back when it is turned off.",
    effect: "Every other output that plays the same mix goes mono with it. The button's own tooltip names them.",
    watch: "It centres the mix's pans on the device and lowers that mix's master by what that gains: about 6 dB where a centred strip loses nothing (the Studio+), less on the Quadro, whose panning law already takes some of it (measured at both devices). A mix that also feeds a recording input records mono meanwhile. Disabled when no one mix feeds this output.",
  },
  "cr.mono-badge": { title: "MONO", what: "The Quadro reports {name} as mono. The app can show this but has no command to change it.", name: "this output" },
  "cr.feed": { title: "What feeds {name}", name: "this output", what: "The mix routed to {name}, or the sources it plays straight, or Muted, from the device's routing." },
  "cr.talk": {
    title: "Talk",
    what: "The Studio+ talkback: on only while you hold it (pointer, Space or Enter), off as soon as you let go.",
    effect: "Sends the talkback microphone to the outputs lit under To, at the talkback level.",
  },
  "cr.talk-level": {
    title: "Talkback level",
    what: "How loud talkback is, as a fader on the outputs' scale: 0 dB at the right, off at the left.",
    effect: "A double-click sets -30 dB, or 0 dB when the header's Double-click menu says unity; Ctrl or Cmd and a click always sets 0 dB.",
  },
  "cr.talk-to": { title: "Talkback to {name}", name: "this output", what: "Whether talkback is heard on {name} while Talk is held." },

  // The mixer dock.
  "dock.section": {
    title: "Mixer dock",
    what: "The mix you picked on the Mixer page as slim strips, so levels can be ridden from any page. Hidden on the Mixer page itself. Whether it is folded is remembered in this browser.",
    effect: "Drop sources dragged from the Routing page here to add a channel for each, fed by it, in the mix shown. Held over a folded dock, the drag opens it.",
    watch: "It adds only to the device the sources belong to: while it shows a surface or another device it refuses the drop and says why.",
  },
  "dock.source": { title: "Dock shows", what: "This device's selected mix, or one of your surfaces, so strips from any device can sit under every page. Remembered in this browser." },
  "dock.mix": { title: "Dock mix", what: "Which of the device's mixes the dock shows. It is the same choice as the Mixer page's Mix buttons: changing one changes the other." },
  "dock.open-mixer": { title: "Open the Mixer page", what: "No channel is set up in this mix yet; channels are set up on the Mixer page." },
  "dock.drop-confirm": {
    title: "Confirm",
    what: "The sources just dropped would put an input into this mix a second time, so the mix would sum it twice, about 6 dB louder. Press Confirm to add them anyway.",
    effect: "Nothing has been added or sent yet. Left alone for a few seconds, the question goes away and nothing is added.",
  },
  "dock.drop-cancel": { title: "Cancel", what: "Adds nothing: the sources just dropped are left out of the mix." },
  "dock.open-surface": { title: "Open the surface", what: "This surface has no strips yet; strips are added on the surface's own page." },

  // Pages in general.
  "page.last-sent": {
    title: "Last command",
    what: "The last command this page sent to the device and its bytes, or in dry run the bytes it would have sent.",
    effect: "It appears only while this explain mode is on, or while the server is in dry run; the rest of the time it stays out of the way.",
  },

  // A mixer strip.
  "strip.fader": {
    title: "{name} fader",
    name: "Channel",
    what: "{name}'s level in the mix you picked, from 0 dB at the top down to -90 dB. The scale is drawn like the meters, so each 10 dB down takes less room.",
    effect: "Changes this channel's level in this mix only; the other mixes keep theirs. A channel linked with it follows. " + LEVEL_KEYS,
    watch: "-90 dB is the floor, not silence: to take a channel out of a mix, mute it.",
  },
  "strip.master-fader": {
    title: "{name} master fader",
    name: "Mix",
    what: "The master level of {name}: everything the mix plays goes through it, from 0 dB down to -90 dB.",
    effect: "Every output and recording input that plays this mix gets louder or quieter together. " + LEVEL_KEYS,
  },
  "strip.pan": {
    title: "{name} pan",
    name: "Channel",
    what: "Where {name} sits between left and right in this mix, from L 100% through C to R 100%.",
    effect: "Dragging snaps to centre near the middle, as the vendor panel's knob does; the wheel and arrow keys step about 3% at a time through it. Double-click centres it. Each channel keeps its own pan, even when linked.",
    watch: "While the mix is mono, the device has the channel centred and this shows the pan it goes back to. On the Quadro the panning law sets how loud a centred channel is.",
  },
  "strip.send": {
    title: "{name} reverb send",
    name: "Channel",
    what: "How much of {name} goes to the Studio+'s reverb, in dB of attenuation: 0 dB at the right, off at the left. Only on Mix 1, as the vendor panel has it.",
    effect: "A double-click turns it off, so it never adds reverb, or sets 0 dB when the header's Double-click menu says unity; Ctrl or Cmd and a click always sets 0 dB. The reverb's level on the Effects page is its return.",
  },
  "strip.mute": {
    title: "{name} mute",
    name: "Channel",
    what: "Mutes {name} in this mix only. Its fader stays where it is.",
    effect: "A channel linked with it follows.",
  },
  "strip.master-mute": {
    title: "{name} master mute",
    name: "Mix",
    what: "Mutes {name} at its master, so the mix goes quiet on every output and recording input it plays on.",
  },
  "strip.solo": {
    title: "{name} solo",
    name: "Channel",
    what: "Sets {name}'s solo in this mix, as the vendor panel's S button does.",
    watch: "How the device plays a solo, which channels it silences and on which outputs, is the device's own behaviour; the app has not measured it.",
  },
  "strip.meter": {
    title: "{name} meter",
    name: "Channel",
    what: "The signal arriving at {name}'s input, before its fader, in dB below full scale from 0 down to -60. Every strip on the same input shows the same meter.",
    effect: "The bar rises fast and falls back at 12 dB a second. The bright marker holds the loudest recent level for 1.5 s, then falls.",
    watch: "It is the input, not the mix: a muted or pulled down channel still shows its input. A strip on an effect return shows its chain's last effect, or what feeds an empty chain.",
  },
  "strip.clip": {
    title: "{name} clip light",
    name: "Channel",
    what: "Lights when {name}'s input reaches full scale. It belongs to the input, so every strip on that input shares it.",
    effect: "Click it to clear it; it also clears by itself after the time set in the Meter section.",
  },
  "strip.level": { title: "Level", what: "The fader's level in dB." },
  "strip.peak": { title: "Peak", what: "The loudest recent level on the meter, in dB below full scale: the value the peak marker holds. Below -60 it reads < -60." },
  "strip.doubled": {
    title: "Summed twice",
    what: "The same audio reaches this mix twice: two channels on one input, or a channel whose empty effect chain passes the other's input straight through.",
    effect: "Summing a signal with itself makes it about 6 dB louder. The badge's own tooltip names the source.",
    watch: "Mute one of the two, or load an effect in the chain, and the badge goes. Dry and wet through a chain with an effect in it is not warned about: that is a parallel setup, and a different signal.",
  },
  "strip.name": {
    title: "{name}",
    name: "Channel",
    what: "The channel's name and colour. The colour is its group's if the group has one, else its own, else its input's colour from the Routing page.",
    effect: "Greyed when the channel is not set up in the mix you picked.",
  },

  // A channel's head on the Mixer page.
  "channel.grip": { title: "Drag to move", what: "Drag the channel by this grip to put it somewhere else in the row. Dropped between two channels of a group, it joins the group. " + NOTHING_SENT },
  "channel.move-left": { title: "Move left", what: "Moves the channel one place left in the row. Only the layout changes. " + NOTHING_SENT },
  "channel.move-right": { title: "Move right", what: "Moves the channel one place right in the row. Only the layout changes. " + NOTHING_SENT },
  "channel.remove": {
    title: "Remove {name}",
    name: "the channel",
    what: "Takes the channel off the mixer. Click twice: the first click arms it for 3 s.",
    watch: "Its input is muted in every mix it fed, so the audio stops there.",
  },
  "channel.name": { title: "Channel name", what: "The channel's name. Left empty, it goes by its input's name. " + WORKSPACE + " " + NOTHING_SENT },
  "channel.colour": { title: "Channel colour", what: "Shows the strip's colour and opens a picker: the theme's colours, any colour, or Clear to go back to the default. A group's colour wins while the channel is in a group with one. " + NOTHING_SENT },
  "channel.input": {
    title: "Channel input",
    what: "Which source feeds this channel: a preamp, a digital input, the computer's playback, an effect return.",
    effect: "Routes that source to the channel's mixer input in its main mix and every mix it is sent to, and mutes it in the rest. No input mutes it everywhere. The wheel does not step this menu, since each step would route.",
  },
  "channel.main-mix": {
    title: "Main mix",
    what: "The mix this channel belongs to. A channel works once it has an input and a main mix.",
    effect: "Routes the channel into that mix. Other mixes can take it too, with Add to on the channel. The wheel does not step this menu.",
  },
  "channel.group": { title: "Group", what: "Puts the channel in a group, or makes a new one. Grouped channels sit together under a coloured band that can fold them away. " + NOTHING_SENT },
  "channel.in-mix": {
    title: "In this mix",
    what: "Whether the channel is in the mix you picked. Its main mix reads Main mix; any other mix can take it as a send.",
    effect: "Add routes the channel's input into this mix; taking it out mutes it there. Its level in each mix is its own.",
    watch: "Adding a channel whose input the mix already has takes two clicks: the first reads Confirm and says what would be summed twice.",
  },
  "channel.doubling-confirm": {
    title: "Confirm",
    what: "The choice beside this would put one input into a mix twice, so that mix would sum it twice, about 6 dB louder. Press Confirm to do it anyway, or pick something else.",
    effect: "Nothing has been sent yet. Left alone for a few seconds, the menu goes back to what it had.",
    watch: "Dry into a mix alongside the same signal through an effect chain is a parallel setup, not a doubling, and is not asked about.",
  },
  "channel.pre-type": {
    title: "{name} type",
    name: "Preamp",
    what: "What {name} expects: Mic, Line, or Hi-Z for an instrument, on the preamps that have it. The same control as the Inputs page's.",
    effect: "Changes the gain range: Mic 0 to 65 dB, Line -6 to +20 dB, Hi-Z 0 to 40 dB.",
    watch: "48V works on Mic only.",
  },
  "channel.pre-gain": {
    title: "{name} gain",
    name: "Preamp",
    what: "{name}'s gain in whole dB, shared with the Inputs page and every channel on this preamp.",
    effect: "Raises or lowers the level before anything else, so every mix and recording of this input follows. " + STEP_KEYS,
    watch: "Too much clips the converter: watch the clip light.",
  },
  "channel.48v": {
    title: "{name} 48V",
    name: "Preamp",
    what: "Phantom power for a condenser microphone on {name}. Mic type only.",
    effect: "Turning it on takes a second click (or Ctrl or Cmd and a click); turning it off is one.",
    watch: "48V can damage a ribbon microphone or gear wired unbalanced, and switching it makes a loud thump: turn the monitors down first.",
  },
  "channel.phase": { title: "{name} phase invert", name: "Preamp", what: "Flips the polarity of {name}'s signal.", effect: "Useful when two microphones on one source cancel each other; on its own it sounds the same." },
  "colour.swatch": { title: "Palette colour", what: "Gives the channel this colour from the theme. " + NOTHING_SENT },
  "colour.custom": { title: "Custom colour", what: "Gives the channel any colour you pick. " + NOTHING_SENT },
  "colour.clear": { title: "Clear the colour", what: "Takes the channel's own colour away, so it shows its input's colour again." },

  // A group band.
  "group.toggle": { title: "Fold the group", what: "Folds the group's channels into a narrow tile, or opens them again. Their levels are untouched. " + NOTHING_SENT },
  "group.name": { title: "Group name", what: "The group's name. " + WORKSPACE },
  "group.colour": { title: "Group colour", what: "The colour every channel in the group shows, over their own." },
  "group.remove": { title: "Remove the group", what: "Removes the group; its channels stay, ungrouped. " + NOTHING_SENT },

  // A mix's master head.
  "master.name": { title: "Mix name", what: "The mix's name, shown in menus and on its master. " + WORKSPACE + " " + NOTHING_SENT },
  "master.mono": {
    title: "Mono",
    what: "Sums this mix to mono. Neither model has a mono switch, so the app pans every channel in the mix to centre and lowers this mix's master by 6 dB, keeping both to put back when it is turned off.",
    effect: "Every output and recording input playing this mix goes mono, at about the level it played before, since summing both sides into each output is about 6 dB louder.",
    watch: "The master fader still works while mono is on. Ending mono gives back only mono's own 6 dB, so a level you rode meanwhile is kept and the mix never ends louder than it started. On the Quadro the panning law sets how loud a centred channel is.",
  },
  "master.outputs": { title: "Where this mix plays", what: "Each output pair this mix is routed to, from the device's routing." },
  "master.output": { title: "{name}", name: "Output", what: "This mix plays on {name}." },
  "master.output-stop": { title: "Stop feeding {name}", name: "this output", what: "Mutes this mix's route to {name} on the device.", watch: "If that is the output you are listening on, it goes quiet." },
  "master.add-output": {
    title: "Add an output",
    what: "Routes this mix to another output pair: a hardware output, or one of the computer's recording inputs.",
    effect: "Choosing one sends the routing to the device at once. The wheel does not step this menu, since every step would add an output.",
    watch: "Whatever that output played before is replaced by this mix.",
  },

  // The link bar and badges.
  "link.mixer": {
    title: "Link",
    what: "Links this channel with others, on this device or another, so a change made here goes to every member: level, mute and solo, in each mix. Pan stays per channel.",
    effect: "Opens the link bar: pick the other channels, choose Same value or Relative, and Save. A number shows which link it is in.",
    watch: "Links are the app's, kept in the workspace. Changes made on the device or in the vendor panel are not repeated to the others.",
  },
  "link.input": {
    title: "Link",
    what: "Links this input with others of its kind, on this device or another, so a change made here goes to every member. A type change goes to every member or to none.",
    effect: "Opens the link bar: pick the other inputs, choose Same value or Relative, and Save. A number shows which link it is in.",
    watch: "48V turned on through a link reaches every member on Mic, and its confirmation says how many.",
  },
  "link.bar": { title: "Link bar", what: "The link being made or changed: its members, and whether they share one value or move by the same step. Pick badges to add or remove members." },
  "link.mode-absolute": { title: "Same value", what: "Every member of the link takes the same value." },
  "link.mode-relative": { title: "Relative", what: "Every member moves by the same step, keeping the offsets between them, each held inside its own range." },
  "link.save": { title: "Save the link", what: "Makes the link, kept in the workspace. Where a link joins exactly one pair on a device, the device's own link flag is set to match, which changes only the vendor panel's controls, not the audio." },
  "link.unlink": { title: "Unlink", what: "Removes the link. Every member keeps its current value." },
  "link.cancel": { title: "Cancel", what: "Closes the link bar without changing anything." },

  // The Mixer page.
  "mixer.mix": {
    title: "Mix",
    what: "Which of the device's four hardware mixes the page shows. One mix is always chosen. Every strip's fader, pan, mute and solo act on that mix, and the meters follow it; each channel keeps its own settings in each mix.",
    effect: "Remembered per device and put in the address, and shared with the mixer dock. Choosing a mix sends nothing.",
  },
  "mixer.show-all": {
    title: "Show all channels",
    what: "Off, the page shows only the channels routed to the chosen mix. On, it shows every channel you have made, with the ones outside this mix dimmed and unmetered, so you can move one in from its head.",
    effect: "Remembered per device in this browser. It changes nothing on the device.",
  },
  "mixer.notes": { title: "How this mixer works", what: "A short note on channels, the mix the faders act on, which channels are shown, and whether the device's levels have been read." },
  "mixer.layout-name": { title: "Layout name", what: "A name for saving these channels, groups and mix names as a layout." },
  "mixer.layout-save": { title: "Save layout", what: "Saves these channels, groups and mix names as a layout any device of this model can start from. " + NOTHING_SENT },
  "mixer.profile": { title: "Start from", what: "A starting layout for this model, or one you saved, to build this mixer from." },
  "mixer.profile-apply": {
    title: "Apply the layout",
    what: "Replaces these channels with the chosen layout and routes it.",
    effect: "With channels already set up, the first click arms it and reads Confirm, and a second click within a few seconds replaces them. With none set up, one click builds the layout.",
    watch: "It sends routing to the device for every channel in the layout, and the channels it replaces are gone unless you saved them as a layout first.",
  },
  "mixer.layout-remove": { title: "Delete the saved layout", what: "Deletes the chosen saved layout from the workspace. " + NOTHING_SENT },
  "mixer.add-channel": { title: "Add a channel", what: "Adds a channel on the next free mixer input. It does nothing until it has an input and a main mix." },
  "mixer.width-auto": { title: "Fit channels", what: "Fits the channels to the window's width, between the narrowest and widest a strip can be. Remembered in this browser." },
  "mixer.width-fixed": { title: "Fixed width", what: "Gives every channel the width set beside it; channels scroll sideways when they do not fit. Remembered in this browser." },
  "mixer.width-px": { title: "Channel width", what: "The width of every channel, in pixels, while Fixed is chosen." },

  // The Inputs page.
  "inputs.preamps": { title: "Preamps", what: "The device's microphone preamps, whether or not a mixer channel uses them." },
  "inputs.digital": { title: "{name}", name: "Digital inputs", what: "The device's {name}. Their gain trims the digital signal as it arrives." },
  "inputs.mic-emulation": { title: "Mic emulation", what: "On the Quadro, which of Antelope's own microphones is on a preamp and which classic microphone it is made to sound like." },
  "inputs.type-mic": {
    title: "{name} Mic",
    name: "Preamp",
    what: "Sets {name} for a microphone: gain 0 to 65 dB, and 48V available.",
  },
  "inputs.type-line": {
    title: "{name} Line",
    name: "Preamp",
    what: "Sets {name} for a line level source such as a synth or another preamp: gain -6 to +20 dB.",
    watch: "48V is off on Line.",
  },
  "inputs.type-hiz": {
    title: "{name} Hi-Z",
    name: "Preamp",
    what: "Sets {name} for an instrument plugged straight in, such as a guitar or bass: gain 0 to 40 dB. Only the first preamps have it (two on the Quadro, four on the Studio+).",
    watch: "48V is off on Hi-Z.",
  },
  "inputs.gain": {
    title: "{name} gain",
    name: "Preamp",
    what: "{name}'s gain in whole dB. Its range follows the type: Mic 0 to 65, Line -6 to +20, Hi-Z 0 to 40.",
    effect: "Raises or lowers the input before anything else, so every mix, recording and effect fed by it follows. " + STEP_KEYS,
    watch: "Too much clips the converter, and that cannot be undone later: watch the clip light on its strips.",
  },
  "inputs.48v": {
    title: "{name} 48V",
    name: "Preamp",
    what: "Phantom power for a condenser microphone on {name}. It exists on Mic only.",
    effect: "Turning it on takes a second click (or Ctrl or Cmd and a click), as the Quadro's panel guards it; turning it off is one click.",
    watch: "48V can damage a ribbon microphone or gear wired unbalanced, and switching it makes a loud thump: turn the monitors down first.",
  },
  "inputs.phase": { title: "{name} phase invert", name: "Preamp", what: "Flips the polarity of {name}'s signal.", effect: "Useful when two microphones on one source cancel each other; on its own it sounds the same." },
  "inputs.hpf": {
    title: "High-pass filter",
    what: "Lit when the device reports its high-pass filter on for this preamp.",
    watch: "Neither model's panel has a command to change it, so the app can only show it.",
  },
  "inputs.digital-gain": {
    title: "{name} gain",
    name: "Input",
    what: "The gain of {name}, -6 to +12 dB in whole dB, applied to the digital signal as it arrives.",
    effect: STEP_KEYS,
  },
  "inputs.digital-gain-readonly": {
    title: "{name} gain",
    name: "Input",
    what: "The gain the device reports for {name}.",
    watch: "The Quadro's own panel never sets this gain, so the app shows it and does not change it.",
  },
  "mic.target": {
    title: "{name} microphone",
    name: "Preamp",
    what: "Which of Antelope's microphones is on {name}, or none. An Edge Duo covers two preamps and an Edge Quadro four.",
    effect: "Picking a microphone that covers more than one preamp links them, so gain and 48V move together.",
    watch: "Every preamp the microphone covers must be on Mic. One the device's licence does not cover is greyed.",
  },
  "mic.model": {
    title: "{name} emulation",
    name: "Preamp",
    what: "Which classic microphone the one on {name} is made to sound like, or the microphone itself. The Edge Quadro has one per head.",
    watch: "One the device's licence does not cover is greyed and cannot be picked.",
  },
  "mic.pattern": {
    title: "{name} polar pattern",
    name: "Preamp",
    what: "Which directions the microphone picks up, from omni through cardioid to figure-8, as far as the emulated microphone allows. Some emulations are fixed at one pattern.",
  },
  "mic.preset": {
    title: "{name} stereo technique",
    name: "Preamp",
    what: "A stereo technique for the Edge Quadro's two heads: XY (both cardioid), Blumlein (both figure-8) or M/S (one of each). Offered only where both heads' emulations can do it.",
    watch: "The technique also wants the top head turned 90 degrees, which is yours to do by hand.",
  },
  "mic.swap": { title: "Swap membranes", what: "Swaps the microphone's front and rear membranes, so its front faces the other way." },
  "mic.plot": {
    title: "Polar pattern",
    what: "How loud the microphone hears each direction, front at the top. A lobe drawn dashed hears in inverted polarity.",
    watch: "Under a stereo technique the heads are drawn turned as the technique wants them, not as they sit: the app cannot see them.",
  },

  // The Outputs page.
  "outputs.hard-mute": {
    title: "Hard mute",
    what: "The Quadro's one switch that mutes every output at once. The vendor panel throws it while it restores a session, so nothing plays through half applied settings.",
    effect: "Every output goes silent until it is switched off again; each output's own volume and mute are kept.",
    watch: "It is a real mute of all four outputs, not the Mute beside one: nothing plays anywhere while it is lit.",
  },
  "outputs.volume": {
    title: "{name} volume",
    name: "Output",
    what: "The hardware volume of {name}, in dB of attenuation: 0 dB at the right, down to off at the left.",
    effect: "Sends the new volume straight to the device. A double-click sets -30 dB, or 0 dB when the header's Double-click menu says unity; Ctrl or Cmd and a click always sets 0 dB.",
    watch: "A drag to the right is as loud as the output goes: turn up slowly on speakers and headphones.",
  },
  "outputs.mute": { title: "{name} mute", name: "Output", what: "Mutes {name} on the device. Its volume is kept and comes back when unmuted." },
  "outputs.dim": {
    title: "{name} dim",
    name: "Output",
    what: "Dims {name}: the Quadro lowers the output by its own dim amount while this is lit.",
    watch: "How many dB the device dims by is its own; the app has not measured it.",
  },
  "outputs.mono": { title: "MONO", what: "The Quadro reports this output as mono. The app can show this but has no command to change it; the Control Room's Mono sums a mix instead." },
  "outputs.in-cr": { title: "{name} in the Control Room", name: "this output", what: "Whether {name} shows in the sidebar's Control Room. " + WORKSPACE + " " + NOTHING_SENT },
  "outputs.trims": { title: "Trims", what: "The output trims, in the seven steps the vendor panel labels 20 dBu down to 14 dBu." },
  "outputs.trim": {
    title: "{name} trim",
    name: "Output",
    what: "{name}'s trim, one of seven steps the vendor panel labels 20 dBu to 14 dBu.",
    watch: "The panel gives the steps in dBu and nothing more; how they relate to full scale on the device has not been measured here.",
  },
  "outputs.talkback": { title: "Talkback", what: "The Studio+'s talkback microphone: talk while held, its level, and which outputs hear it." },
  "outputs.talk": {
    title: "Talk",
    what: "The Studio+ talkback: on only while you hold it (pointer, Space or Enter), off as soon as you let go, however it is let go.",
  },
  "outputs.talk-level": { title: "Talkback level", what: "How loud talkback is, as a fader on the outputs' scale: 0 dB at the right, off at the left.", effect: "A double-click sets -30 dB, or 0 dB when the header's Double-click menu says unity; Ctrl or Cmd and a click always sets 0 dB." },
  "outputs.talk-to": { title: "Talkback to {name}", name: "this output", what: "Whether talkback is heard on {name} while Talk is held." },

  // The Routing page.
  "routing.read": { title: "Read from device", what: "Reads every destination's routing from the device again, to see changes made elsewhere." },
  "routing.sources": { title: "Sources", what: "Everything that can feed a destination: preamps, digital inputs, the computer's playback, mixes, effect returns. Pick one, or shift-click for a run." },
  "routing.destinations": { title: "Destinations", what: "Everything a source can go to: outputs, the computer's recording inputs, effect chains, and the mixers' inputs. Each channel takes one source; a source can feed any number." },
  "routing.source": {
    title: "{name}",
    name: "Source",
    what: "A source channel. Click to select it, shift-click to select a run from the last one picked. Then click a destination cell, or drag onto one.",
    effect: "Selecting sends nothing; the destination click does. Dragged onto the Mixer dock instead, each selected source becomes a new channel in the dock's mix, as if made on the Mixer page.",
    watch: "Dragging to the dock needs a mouse; on a touch screen, drag onto destination cells only.",
  },
  "routing.cell": {
    title: "{name}",
    name: "Destination",
    what: "One destination channel and the source feeding it (off when muted).",
    effect: "Click it with sources selected to route them here: a run fills this cell and the ones after it. Delete or Backspace mutes it.",
    watch: "What was routed here is replaced. On an output you are listening through, that changes what you hear at once.",
  },
  "routing.cell-mixer": { title: "{name}", name: "Mixer input", what: "A mixer input and the source feeding it. Mixer inputs are set by the Mixer page's channels, so they are shown here and not changed." },
  "routing.mute-row": { title: "Mute row", what: "Mutes every channel of this destination on the device.", watch: "On an output you are listening through, it goes quiet at once." },
  "routing.mute-row-mixer": { title: "Mute row", what: "Mixer inputs are set by the Mixer page's channels, so this row cannot be muted here." },

  // The Effects page.
  "effects.read": { title: "Read from device", what: "Reads the chains, the reverb and its sends and returns from the device again." },
  "effects.chains": { title: "Effect chains", what: "Each chain processes what routing sends to its AFX IN channel and returns it on AFX OUT. The Quadro has six, the Studio+ sixteen, each up to eight effects in order." },
  "effects.chain-source": { title: "What feeds this chain", what: "The source routed to this chain's AFX IN channel, from the device's routing. Change it on the Routing page." },
  "effects.chain-link": { title: "Linked chain", what: "The device reports this chain linked with its partner. Links are shown here, not changed; a change to one effect goes to the same effect in the partner." },
  "effects.effect": {
    title: "{name}",
    name: "Effect",
    what: "An effect in the chain, with its instance number. Click to open its settings below the chains.",
  },
  "effects.move-up": {
    title: "Move earlier",
    what: "Moves the effect one place earlier in the chain. The whole chain is written and read back.",
    watch: "Reordering a chain has never been tried on a device.",
  },
  "effects.move-down": {
    title: "Move later",
    what: "Moves the effect one place later in the chain. The whole chain is written and read back.",
    watch: "Reordering a chain has never been tried on a device.",
  },
  "effects.remove": {
    title: "Remove the effect",
    what: "Takes the effect out of the chain. The whole chain is written and read back, and the device switches the effect off as it goes.",
  },
  "effects.on": {
    title: "Process",
    what: "The effect processes the signal. Neither On nor Bypass shows lit until the effect's settings are read or you set one.",
  },
  "effects.bypass": {
    title: "Bypass",
    what: "The signal passes the effect untouched. The effect keeps its settings.",
    effect: "A linked chain's same effect follows.",
  },
  "effects.meter": {
    title: "Effect meter",
    what: "The effect's output level in dB below full scale, with a clip light, and GR, the gain reduction the device reports.",
    watch: "GR is shown in the device's own steps: the vendor panel reads it as dB for some effects and quarter dB for others.",
  },
  "effects.no-meter": { title: "No meter", what: "The device reports no meter for this effect." },
  "effects.clip": { title: "Effect clip light", what: "Lights when the effect's output reaches full scale. Click it to clear it." },
  "effects.add": {
    title: "Add an effect",
    what: "Every effect type this model has. One with no free instance left is greyed rather than left out.",
    effect: "Choosing one puts it after what is in the chain, on the lowest free instance, then writes the chain and reads it back. The wheel does not step this menu.",
    watch: "Adding more than one effect to a chain, and the Studio+'s chains, have not been tried on a device.",
  },
  "effects.bypass-all": { title: "Bypass all", what: "Bypasses every effect in this chain." },
  "effects.process-all": { title: "Process all", what: "Sets every effect in this chain processing." },
  "effects.editor": { title: "{name}", name: "Effect", what: "The settings of the effect you chose, as the vendor panel's code describes them." },
  "effects.editor-close": { title: "Close", what: "Closes the effect's settings." },
  "effects.param-range": {
    title: "{name}",
    name: "Setting",
    what: "One of the effect's settings, as a range.",
    effect: "Each change sends every setting of this effect with the new value. A double-click puts it back to the vendor panel's starting value.",
    watch: "A value without a unit is the device's own step: the vendor panel draws its scale in artwork the app does not copy.",
  },
  "effects.param-switch": { title: "{name}", name: "Setting", what: "One of the effect's settings, as a switch.", effect: "Each change sends every setting of this effect. A double-click puts it back to the starting value." },
  "effects.param-menu": { title: "{name}", name: "Setting", what: "One of the effect's settings, chosen from a list.", effect: "Each change sends every setting of this effect. A double-click puts it back to the starting value." },
  "effects.param-bits": { title: "{name}", name: "Setting", what: "One of the effect's settings, as buttons that each switch one part of it on or off." },
  "effects.band": { title: "{name}", name: "Band", what: "One band of the equaliser. A change sends only this band.", watch: "While the band is a high-pass or low-pass filter, its gain is off." },

  // The reverb.
  "reverb.heading": { title: "Reverb", what: "The device's one reverb: on or off and its level here; its other settings as the device reports them." },
  "reverb.on": { title: "Reverb on", what: "Switches the device's reverb on or off. Sent only once its settings have been read, so the other settings are never overwritten with defaults." },
  "reverb.level": { title: "Reverb level", what: "The level of the reverb's output. On the Studio+ this is its return.", effect: "A double-click sets -18 dB, the nearest its steps have to -20, or 0 dB when the header's Double-click menu says unity; Ctrl or Cmd and a click sets 0 dB." },
  "reverb.param": { title: "{name}", name: "Reverb setting", what: "A reverb setting as the device reports it, in the vendor panel's units.", watch: "Changing it is not in this version." },
  "reverb.returns": { title: "Reverb returns", what: "How much reverb each of the Quadro's first two mixes gets back." },
  "reverb.return-level": {
    title: "{name}",
    name: "Reverb return",
    what: "How much reverb goes back into this mix, in the vendor panel's own steps: 0 is full, 90 the least.",
    effect: "A double-click sets 20 steps below full; Ctrl or Cmd and a click sets full.",
    watch: "The panel shows no scale for these, and they have not been checked on the device.",
  },
  "reverb.return-mute": { title: "Mute the return", what: "Mutes the reverb coming back into this mix." },
  "reverb.sends": { title: "Reverb sends", what: "How much of each of mix 1's channels 1 to 16 goes to the Quadro's reverb, and where it sits in it." },
  "reverb.send-level": { title: "{name}", name: "Reverb send", what: "How much of this channel goes to the reverb, in dB of attenuation: 0 dB at the right, off at the left.", effect: "A double-click turns it off, so it never adds reverb, or sets 0 dB when the header's Double-click menu says unity; Ctrl or Cmd and a click always sets 0 dB." },
  "reverb.send-pan": { title: "{name}", name: "Reverb send pan", what: "Where this channel sits in the reverb, from L 100% through C to R 100%.", effect: "Dragging snaps to centre near the middle; a double-click centres it." },

  // The Devices page.
  "devices.device": { title: "Device", what: "The device's identity as the server sees it, and the name you give it." },
  "devices.status": { title: "Status report", what: "A few values live from the report the device sends many times a second." },
  "devices.clock": { title: "Clock", what: "Where the device takes its clock from, the sample rate, and what it measures." },
  "devices.panning": { title: "Panning law", what: "How much the Quadro turns down a centred signal in every mix." },
  "devices.dc": { title: "DC coupling", what: "Whether the Quadro's converters pass DC, for control voltages." },
  "devices.oscillator": { title: "Test oscillator", what: "A sine tone per side straight to the outputs, for lining up a signal path." },
  "devices.presets": { title: "Presets", what: "The device's own five preset slots, kept in the device's memory, not the workspace." },
  "devices.name": { title: "Device name", what: "The name shown on the device's card and in menus. Left empty, it goes by the model. " + WORKSPACE + " " + NOTHING_SENT },
  "devices.model": { title: "Model", what: "The device's model, from its USB identity." },
  "devices.family": { title: "Family", what: "The command set the server speaks to this device: quadro or studio, or unknown." },
  "devices.id": { title: "Id", what: "The server's id for this device. A real device's comes from its serial number." },
  "devices.usb-id": { title: "USB id", what: "The device's USB vendor and product ids." },
  "devices.backend": { title: "Backend", what: "How the server reaches this device: usb for the real interface, loopback for the emulator." },
  "devices.identity": { title: "Identity", what: "Whether the device keeps the same id when it is plugged in again." },
  "devices.live-power": { title: "Power", what: "Whether the device reports itself on or in standby." },
  "devices.live-preset": { title: "Preset", what: "The preset slot the device reports it is on." },
  "devices.live-sync": { title: "Sync source", what: "The clock source the device reports, as its index in the device's list." },
  "devices.power-on": { title: "Power on", what: "Wakes the device from standby." },
  "devices.standby": {
    title: "Standby",
    what: "Puts the device in standby. Click twice: the first click arms it for 3 s.",
    watch: "Standby stops the device's audio: everything playing through it stops.",
  },
  "devices.brightness": { title: "Front-panel brightness", what: "How bright the device's front panel is, 0 to 100%.", effect: "It has no effect on the audio. The bar shows what the device reports." },
  "devices.preset-recall": {
    title: "Recall preset {name}",
    name: "",
    what: "Loads the device's preset from this slot. The slot the device is on is lit.",
    effect: "Click twice: the first click arms it for 3 s and the button reads Confirm.",
    watch: "A preset may hold anything, 48V and the clock among it, and recalling it changes all of it at once, which can change what you hear.",
  },
  "devices.preset-slot": { title: "Save into", what: "The slot Save writes into. Choosing one writes nothing." },
  "devices.preset-save": {
    title: "Save preset",
    what: "Saves the device's current state into the chosen slot. Click twice: the first click arms it for 3 s.",
    watch: "It overwrites what is in that slot.",
  },
  "devices.clock-source": {
    title: "Clock source",
    what: "Where the device takes its clock from: its own (Internal on the Quadro, the oven clock on the Studio+), or a digital input, word clock (Studio+) or USB.",
    effect: "Choosing another shows Confirm beside the menu; nothing is sent until it is pressed, and a wait of 3 s puts the menu back.",
    watch: "Changing it reclocks the device, which interrupts whatever is playing through it. A source with no signal behind it loses lock. The wheel does not step this menu for that reason.",
  },
  "devices.sample-rate": {
    title: "Sample rate",
    what: "The rate the device runs at, 32 to 192 kHz.",
    effect: "Choosing another shows Confirm beside the menu; nothing is sent until it is pressed, and a wait of 3 s puts the menu back.",
    watch: "Changing it interrupts everything playing through the device, including a DAW's stream. While the device follows an external clock it takes the rate from there and ignores this. The wheel does not step this menu.",
  },
  "devices.clock-confirm": {
    title: "Confirm",
    what: "Sends the clock source or sample rate chosen in the menu beside it. Its own tooltip names the choice.",
    watch: "Audio through the device stops for a moment while it reclocks.",
  },
  "devices.measured": { title: "Measured", what: "The sample rate the device measures, as it reports it; none when it measures nothing." },
  "devices.lock": { title: "Lock", what: "Whether the device reports itself locked to its clock source." },
  "devices.spdif-src": {
    title: "S/PDIF sample-rate converter",
    what: "The Studio+'s converter on its S/PDIF input: on, a source at another rate or on another clock is converted, so it need not be the clock.",
    watch: "What the panel's label says is in a bitmap the app cannot read; the meaning is from the manual and users, and still to check on the device.",
  },
  "devices.panning-law": {
    title: "Panning law",
    what: "How much a centred signal is turned down in every mix: 0, -3, -4.5 or -6 dB.",
    effect: "Every pan is heard through it, and so is Mono, which works by centring pans and taking 6 dB off the mix.",
  },
  "devices.dc-inputs": {
    title: "DC coupled inputs",
    what: "Lets the Quadro's inputs pass control voltages as well as audio, for modular gear.",
    effect: "Turning it on takes a second click within 3 s; turning it off is one.",
    watch: "Leave it off for audio: with it on, any DC offset a source carries comes in too.",
  },
  "devices.dc-outputs": {
    title: "DC coupled outputs",
    what: "Lets the Quadro's outputs pass control voltages as well as audio, for modular gear.",
    effect: "Turning it on takes a second click within 3 s; turning it off is one.",
    watch: "Leave it off for audio: with it on, any DC in what is played reaches the outputs, which speakers and headphones should never get.",
  },
  "devices.osc-frequency": { title: "{name} frequency", name: "Oscillator", what: "The tone's frequency: 1 kHz or 440 Hz." },
  "devices.osc-tone": {
    title: "{name} tone",
    name: "Oscillator",
    what: "Switches this side's test tone on or off.",
    effect: "Turning it on takes a second click within 3 s; turning it off is one.",
    watch: "At 0 dBFS the tone is as loud as the device goes: turn the monitors down first.",
  },
  "devices.osc-level": { title: "Oscillator level", what: "The tones' level, shared by both sides: 0, -6, -12 or -18 dBFS.", watch: "0 dBFS is full scale." },
  "devices.driver": {
    title: "Driver",
    what: "The USB audio driver's settings on this computer for this device, not the device's own. Read from the driver itself; the buffer size and Safe Mode can be changed here, each with a confirming click.",
    watch: "A program using the driver (a DAW) restarts its audio when either changes.",
  },
  "devices.driver-version": { title: "Driver version", what: "The driver's version and the version of its programming interface. One Gazelle was not checked against says so." },
  "devices.driver-rate": { title: "Sample rate", what: "The sample rate the driver reports it is running at for this device." },
  "devices.driver-buffer": {
    title: "Buffer size",
    what: "The driver's ASIO buffer, in samples: smaller means less delay through the computer, larger means fewer dropouts.",
    watch: "A DAW using the driver has to restart its audio when the buffer changes, so expect a gap or a prompt from it.",
  },
  "devices.driver-buffer-menu": {
    title: "Buffer size",
    what: "The ASIO buffer the driver uses, from the sizes it offers. Choosing one shows a Confirm beside the menu; nothing is sent until it is pressed.",
    effect: "Smaller means less delay through the computer, larger means fewer dropouts. The latencies below show what the driver reports after the change.",
    watch: "A DAW using the driver restarts its audio. The wheel does not change this menu.",
  },
  "devices.driver-buffer-confirm": {
    title: "Confirm",
    what: "Sends the buffer size chosen in the menu beside it to the driver, keeping Safe Mode as it is, then shows what the driver reports. A wait puts the menu back.",
    watch: "A DAW using the driver restarts its audio.",
  },
  "devices.driver-safe-mode-switch": {
    title: "Safe Mode",
    what: "Turns the driver's ASIO Safe Mode on or off, keeping the buffer size as it is. The first click reads Confirm; a second within three seconds sends.",
    effect: "Measured on a Quadro: it adds 176 samples of output latency at 256 samples and 265 at 512, and nothing to the input.",
    watch: "A DAW using the driver restarts its audio.",
  },
  "devices.driver-force": {
    title: "Change anyway",
    what: "Sends the change the driver section refused because a program is using the driver's ASIO interface, this time anyway. It takes a confirming click.",
    watch: "That program (a DAW, most likely) restarts its audio, and may stop or complain.",
  },
  "devices.driver-result": {
    title: "Result",
    what: "What happened to the last change: what the driver reports now, with its latencies, or why nothing was sent. A result that differs from what was sent says so.",
  },
  "devices.driver-latency": { title: "Latency", what: "The delay the driver reports, in samples and in milliseconds at its sample rate, rounded as the vendor's panel rounds it." },
  "devices.driver-safe-mode": {
    title: "Safe Mode",
    what: "The driver's ASIO Safe Mode, which adds buffering for fewer dropouts at the cost of more delay.",
    effect: "Measured on a Quadro at 256 samples: it adds 176 samples, about 4 ms, to the output latency and nothing to the input.",
  },
  "devices.driver-refresh": { title: "Read again", what: "Asks the driver again now, rather than using what was read in the last few seconds. It changes nothing." },

  // The Workspace page.
  "workspace.saving": { title: "Saving", what: "The workspace is being saved to the server. Edits save by themselves a moment after you make them." },
  "workspace.names": { title: "Device names", what: "The name and badge colour of every connected device." },
  "workspace.surfaces": { title: "Surfaces", what: "Rows of strips from any devices side by side, each opened on a page of its own." },
  "workspace.cables": { title: "Digital cables", what: "Which digital output is plugged into which input, so surfaces can say where a signal comes from and warn when the clocks disagree." },
  "workspace.groups": { title: "Groups", what: "The workspace's groups, with their colours." },
  "workspace.snapshots": { title: "Snapshots", what: "Named records of the workspace and every attached device's state, to compare with now." },
  "workspace.backup": { title: "Backup", what: "Export the workspace to a file, or replace it with one." },
  "workspace.device-id": { title: "Device id", what: "The server's id for the device." },
  "workspace.device-name": { title: "Device name", what: "The name shown on the device's card and in menus. Left empty, it goes by the model. " + NOTHING_SENT },
  "workspace.device-colour": { title: "Badge colour", what: "The colour of this device's badge on surface strips, so two devices' strips never read as one mixer. " + NOTHING_SENT },
  "workspace.device-colour-clear": { title: "Clear the colour", what: "Goes back to the theme's colour for this device's badge." },
  "workspace.group-toggle": { title: "Fold the group", what: "Folds or opens the group in this list and on the Mixer page." },
  "workspace.group-no-colour": { title: "No colour", what: "The group has no colour of its own, so its channels show theirs." },
  "workspace.group-colour": { title: "Group colour", what: "Gives the group this colour, which its channels show over their own." },
  "workspace.surface-name": { title: "Surface name", what: "The surface's name; edit it in place." },
  "workspace.surface-open": { title: "Open", what: "Opens the surface on a page of its own." },
  "workspace.surface-delete": { title: "Delete the surface", what: "Deletes the surface. Click twice. Nothing changes on the devices: a surface is only what to show." },
  "workspace.surface-new-name": { title: "New surface name", what: "A name for a new surface." },
  "workspace.surface-create": { title: "New surface", what: "Makes an empty surface with the name beside it." },
  "workspace.cable-from": { title: "Cable from", what: "The digital output the cable leaves, on any attached device." },
  "workspace.cable-to": { title: "Cable to", what: "The digital input of the same kind the cable goes into, on another device." },
  "workspace.cable-channels": { title: "Channels", what: "How many channels the cable carries: up to 2 for S/PDIF, 8 for ADAT." },
  "workspace.cable-declare": {
    title: "Declare cable",
    what: "Records that this cable is plugged in.",
    watch: "A cable only says what is plugged in. It routes nothing and changes no clock; set those on each device.",
  },
  "workspace.cable-health": { title: "What is wrong along it", what: "Warnings from both devices' reports: sample rates that differ, a receiver not locked, or signal leaving one end and none arriving at the other." },
  "workspace.cable-remove": { title: "Remove the cable", what: "Removes the cable from the workspace. Click twice. Nothing changes on the devices." },
  "workspace.snapshot-name": { title: "Snapshot name", what: "The snapshot's name; edit it in place." },
  "workspace.snapshot-compare": { title: "Compare with now", what: "Reads every device again and shows what differs from the snapshot. Nothing is sent." },
  "workspace.snapshot-delete": { title: "Delete the snapshot", what: "Deletes the snapshot from the server. Click twice." },
  "workspace.snapshot-new-name": { title: "New snapshot name", what: "A name for the snapshot to take." },
  "workspace.snapshot-take": { title: "Take snapshot", what: "Reads every attached device's mixer, routing, inputs, outputs, clock and settings, and keeps them with the workspace under this name.", effect: "Only reads: nothing is sent to a device. Not possible in dry run, where reads answer nothing." },
  "workspace.snapshot-prepare": {
    title: "Prepare recall",
    what: "Reads the devices again and lists, in order, every command putting this snapshot back would send, with its guards and bytes.",
    watch: "It is a preview only: putting a snapshot back is not built yet, and nothing is sent.",
  },
  "workspace.snapshot-close": { title: "Close", what: "Closes the comparison." },
  "workspace.export": { title: "Export", what: "Downloads the workspace as a dated JSON file." },
  "workspace.export-all": { title: "Export with snapshots", what: "Downloads the workspace and every snapshot in one file." },
  "workspace.import-file": { title: "Workspace file", what: "A workspace file, or a backup with snapshots, to import." },
  "workspace.import": { title: "Import", what: "Reads the chosen file, says what it holds and asks before replacing anything." },
  "workspace.import-replace": {
    title: "Replace workspace",
    what: "Replaces the whole workspace with the file's, for everyone using this server. Snapshots it holds are added.",
    watch: "Export first if you may want the current one back. A workspace is layout only, so nothing is sent to a device.",
  },
  "workspace.import-cancel": { title: "Cancel", what: "Leaves the workspace as it is." },

  // A surface.
  "surface.name": { title: "Surface", what: "A row of strips from any devices side by side. Every control on a strip sends what the device's own page would, to that device." },
  "surface.to-workspace": { title: "Workspace page", what: "Surfaces are made and deleted on the Workspace page." },
  "surface.mix": { title: "{name} mix", name: "Device", what: "Which mix the surface shows for {name}'s channels and master, unless a strip is pinned to its own. Kept with the surface." },
  "surface.clock": { title: "Clock", what: "The device's sample rate, clock source and lock, followed while the surface is open: two devices joined by a cable must agree." },
  "surface.cable-health": { title: "Cable", what: "A cable between two devices on this surface, and anything wrong along it: rates that differ, no lock, or signal that leaves and never arrives." },
  "surface.grip": { title: "Drag to move", what: "Drag the strip by this grip to move it along the surface." },
  "surface.move-left": { title: "Move left", what: "Moves the strip one place left on the surface. " + NOTHING_SENT },
  "surface.move-right": { title: "Move right", what: "Moves the strip one place right on the surface. " + NOTHING_SENT },
  "surface.pin": { title: "Mix this strip shows", what: "Follow the surface's mix for this device, or keep this strip to one mix. The wheel does not step this menu." },
  "surface.remove": { title: "Take off the surface", what: "Takes the strip off the surface. Click twice. Nothing changes on the device." },
  "surface.add-device": { title: "Strip device", what: "The device the new strip comes from." },
  "surface.add-kind": { title: "Strip kind", what: "What to add: a mixer channel, a mix master, an input, an output, a digital output, both ends of a cable, or a label." },
  "surface.add-item": { title: "Strip item", what: "Which one of that kind on that device." },
  "surface.add-text": { title: "Label text", what: "The text of a label strip." },
  "surface.add": { title: "Add strip", what: "Puts the chosen strip at the end of the surface. " + NOTHING_SENT },
  "surface.badge": { title: "{name}", name: "Device", what: "The device this strip belongs to, in its badge colour, so strips from two devices never read as one mixer." },
  "surface.caption": { title: "Which mix", what: "The mix the strip shows, or which part of a digital output; pinned when it keeps to one mix." },
  "surface.provenance": { title: "Where it comes from", what: "A declared cable brings this input's signal from another device, and what that device routes to its end." },
  "surface.input-level": { title: "Input level", what: "The input's signal as it arrives, on the meters' scale." },
  "surface.src": {
    title: "S/PDIF SRC",
    what: "The Studio+'s sample-rate converter on its S/PDIF input: on, this device need not follow the sender's clock.",
    watch: "Its meaning is from the manual and users, and still to check on the device.",
  },
  "surface.port-feed": { title: "What feeds this pair", what: "The mix or source routed to this pair of the digital output, or Muted, from the device's routing." },
  "surface.port-route": {
    title: "Route to this pair",
    what: "Routes a mix, a source bit for bit, or nothing to this pair of the digital output, on the device that owns it.",
    effect: "One routing write to the device; the rest of the port is kept. The wheel does not step this menu.",
    watch: "A source routed bit for bit has no level: neither model has a volume for its digital outputs.",
  },
  "surface.port-level": { title: "Output level", what: "The level the Quadro reports leaving its S/PDIF output." },
  "surface.port-master": { title: "Master feeding the port", what: "This mix feeds the digital output, so its master fader is that output's level." },

  // The Aggregate page.
  "aggregate.verdict": {
    title: "Ready or not ready",
    what: "Whether a DAW could open Gazelle Aggregate right now and get working audio out of it. Not ready means at least one of the reasons below stops it.",
    effect: "Read from the server every time the page asks, which is every second while a DAW is playing and more slowly when it is not.",
  },
  "aggregate.refresh": { title: "Read again", what: "Asks the server for the whole answer now, rather than waiting for the next time the page asks by itself.", effect: "It reads the audio drivers on this PC, which takes a moment. Nothing is sent to a device." },
  "aggregate.ready": { title: "Ready to use", what: "Everything between you and a working aggregate, in the order it matters: what is missing, then the machine, then the clock." },
  "aggregate.severity": {
    title: "How much it matters",
    what: "STOPS IT is a reason the aggregate will not work at all. WORTH KNOWING is something to be aware of that does not stop it.",
  },
  "aggregate.fix": {
    title: "Put it right",
    what: "Sends exactly the request the server prepared for this reason: matching the buffer sizes, putting a device on the right clock or rate, or registering the driver.",
    effect: "Afterwards the whole answer is read again, so what you see is what the server makes of it, not what the button hoped for.",
    watch: "Matching buffer sizes restarts the audio of every program using those drivers, so it asks for a second click first.",
  },
  "aggregate.reason-goto-phase": {
    title: "Set up the phase",
    what: "Opens the phase setup on the card of the interface this reason is about, where you say which channel the digital cable leaves the callback master on and which it arrives on.",
    effect: "It only opens the card. Nothing is written until both channels are chosen there.",
  },
  "aggregate.outcome": { title: "What that came to", what: "What the last button pressed here actually did, in the server's own words." },
  "aggregate.registration": {
    title: "Registration",
    what: "Whether Windows lists Gazelle Aggregate as an audio driver, and which copy of the file its registration points at. A DAW will not offer it until it is registered.",
  },
  "aggregate.registered": { title: "Registered", what: "Whether Windows has Gazelle Aggregate in its list of audio drivers." },
  "aggregate.driver-name": { title: "What a DAW lists it as", what: "The name to look for in a DAW's audio driver menu." },
  "aggregate.registered-dll": { title: "Registration points at", what: "The file Windows will load when a DAW opens the aggregate. It is the copy that was registered, which need not be the copy that is here now." },
  "aggregate.dll-present": {
    title: "That file is there",
    what: "Whether the file the registration names still exists. Moving or replacing Gazelle leaves a registration pointing at a copy that has gone.",
    effect: "When it has gone, Register it again points the registration at the copy that is here now.",
  },
  "aggregate.found-dll": { title: "The copy Gazelle would register", what: "Where Gazelle found the driver file, or every place it looked when it found none." },
  "aggregate.register": {
    title: "Register the driver",
    what: "Puts Gazelle Aggregate into Windows' list of audio drivers, so a DAW can choose it.",
    effect: "Windows puts up its own administrator prompt. This is the one thing in Gazelle that asks for administrator rights, because the list is shared by every program on the PC.",
    watch: "Declining the prompt changes nothing. The same command is shown below for anyone who would rather run it themselves.",
  },
  "aggregate.unregister": {
    title: "Unregister",
    what: "Takes Gazelle Aggregate out of Windows' list of audio drivers. Click twice.",
    effect: "Windows asks for administrator rights again. A DAW that had it selected will have to be pointed at another driver.",
  },
  "aggregate.devices": { title: "Interfaces", what: "What the aggregate opens, in the order their channels appear to a DAW, with what each one is doing now and the controls to change it." },
  "aggregate.device-name": {
    title: "Name",
    what: "This interface's name, which is the device's name in Gazelle, as the sidebar shows it: the name you gave the device, or its model. The DAW is given the same name.",
    effect: "Nothing to type here. Rename the device on the Devices or Workspace page and it is renamed here, and in the DAW at the driver's next reset.",
    watch: "A DAW puts this name after each channel's, all in 31 characters, so a short name keeps it there; a long one leaves the channel's name alone.",
  },
  "aggregate.device-entry": { title: "Audio driver", what: "The interface's own audio driver this entry opens, as Windows registers it. It is what the aggregate opens, not a name the interface goes by." },
  "aggregate.device-id": {
    title: "Gazelle device",
    what: "Which of the interfaces Gazelle is connected to this one is. It is how its clock, rate and buffer size can be read and changed from here.",
    effect: "Gazelle works it out by itself where the model and what is connected leave one answer. Choosing one here pins it; Work it out hands it back.",
    watch: "Pin one when two units of the same model are connected, because then nothing else can tell them apart.",
  },
  "aggregate.device-worked-out": {
    title: "Worked out",
    what: "Nobody chose this device: Gazelle settled on it from the model and what is connected, and everything on this card is read from it.",
    effect: "Choosing a device in the menu beside this pins it, so it stops being worked out afresh each time.",
  },
  "aggregate.device-channels": {
    title: "Channels",
    what: "How many channels this interface has in the aggregate, how many of them it exposes, and how many you have given a name of your own. They are its USB channels, so the count is known without a DAW.",
  },
  "aggregate.device-channels-open": {
    title: "Channels",
    what: "Opens the list of this interface's channels, which are its USB record and playback channels, where each one can be kept out of what a DAW sees or given a name of your own.",
    effect: "Opening and closing it changes nothing. It stays as you leave it while the app is open.",
  },
  "aggregate.channel-expose": {
    title: "Expose this channel",
    what: "Whether the aggregate offers this channel to a DAW at all. Off keeps it out, so a DAW never sees it.",
    effect: "Saved in the workspace and written out for the driver. A DAW using the aggregate sees the change at its next buffer change.",
    watch: "Taking a channel out moves the numbering of the ones after it, so a DAW session may need its tracks pointing at the right inputs again.",
  },
  "aggregate.channel-name": {
    title: "Channel",
    what: "What this channel is called: what it carries first, then the USB channel it is. An input is named for what the routing sends to its USB record channel, as the Routing page and the Mixer name it; an output for where the routing sends its USB playback channel: the output it reaches, directly or through a mix, else the mix channel it lands in, else not routed.",
    effect: "Nothing to press. Re-routing the channel renames it, here and in the DAW, because it says what would be recorded.",
  },
  "aggregate.channel-label": {
    title: "A name of your own",
    what: "A name for this channel that wins over the one from the routing, here and in the DAW. Empty takes the automatic one, shown beside it. Up to 31 characters.",
    effect: "Saved in the workspace and written out for the driver when you press Enter or leave the field. Clear it and the name from the routing comes back.",
  },
  "aggregate.plays": {
    title: "Where the DAW can play",
    what: "Each output on this interface, monitors first, and which of its USB playback channels reach it: through a mix, directly, or not at all. A left and right pair is one line, and a larger group a line per socket. A channel the DAW plays is only heard where one of these lines says it goes.",
  },
  "aggregate.play-line": {
    title: "What reaches this output",
    what: "The USB playback channels that reach this output, and how: through a mix, named as you named it, or directly. Nothing from the DAW reaches it means the DAW cannot be heard here as the routing stands. Not read yet means Gazelle has not read that routing.",
  },
  "aggregate.play-send": {
    title: "Send DAW channels here",
    what: "Routes the first free USB playback channels, ones that go nowhere and are in no mix, straight to this output, so the DAW can play here. Click twice.",
    effect: "One routing change to this output, the same as making it on the Routing page. The output stops playing whatever feeds it now; the button's tip says what that is.",
  },
  "aggregate.records": {
    title: "Where the DAW can record",
    what: "Each input socket on this interface, in its own order, and which of its USB record channels carry it: directly, through a mix or an effect whose output is recorded, or not at all. A pair of sockets is one line, and a larger group a line per socket. The DAW only records an input one of these lines says is carried.",
  },
  "aggregate.record-line": {
    title: "What records this input",
    what: "The USB record channels that carry this input, and how: directly, through a mix, named as you named it, or through an effect. Nothing records it means the DAW cannot record it as the routing stands. Not read yet means Gazelle has not read that routing.",
  },
  "aggregate.record-send": {
    title: "Record this input",
    what: "Routes this input straight to the first free USB record channels, ones routed from nothing, so the DAW can record it. A pair takes a pair, and a single socket one channel. Click twice.",
    effect: "One routing change to the USB record channels, the same as making it on the Routing page. Those channels were recording nothing, and the aggregate's input names follow the new routing.",
  },
  "aggregate.channel-daw": {
    title: "In a DAW",
    what: "The name a DAW will show for this channel: its name, with the interface's name and the channel's number after it, all in 31 characters. A device you have not named goes by its model's short form here, Quadro or Studio+. Shown only when it says something the channel's name does not.",
    watch: "When that does not fit, the DAW shows the channel's name alone. A short name for the device keeps the rest.",
  },
  "aggregate.device-clock": {
    title: "Clock source",
    what: "What this interface says it is clocked from, as it reports it now.",
    watch: "It has to be read while the interface is streaming: one left on internal quietly becomes USB clocked the moment a DAW opens it, and then it drifts.",
  },
  "aggregate.device-lock": { title: "Lock", what: "Whether the interface says it is locked to its clock source. Not locked means its clock is missing or wrong." },
  "aggregate.device-rate": { title: "Rate", what: "The sample rate this interface reports. Every interface in the aggregate has to be on the same one." },
  "aggregate.device-gap": {
    title: "Gap",
    what: "How far this interface's sample count is from the one driving the callback, while both are streaming. In step is the good reading.",
    effect: "Nothing to press. It is the number that says whether the clock link is holding.",
  },
  "aggregate.device-buffer": {
    title: "Buffer size",
    what: "The audio driver's buffer size for this interface, the same setting the Devices page shows. Every interface in the aggregate has to be on the same one.",
    effect: "Choosing shows a Confirm; only Confirm sends it. Every program using this driver restarts its audio.",
  },
  "aggregate.device-buffer-confirm": { title: "Confirm the buffer size", what: "Sends the size chosen beside it to this interface's driver.", effect: "Every program using the driver, a DAW included, restarts its audio." },
  "aggregate.device-safe": {
    title: "Safe Mode",
    what: "The audio driver's Safe Mode for this interface, the same setting the Devices page shows. It buys stability with latency.",
    effect: "Click twice. Every program using the driver restarts its audio.",
  },
  "aggregate.device-in-trim": {
    title: "Input trim",
    what: "Samples added to what this interface's driver says its input latency is. An interface that records late takes a positive trim.",
    effect: "Saved in the workspace and written out for the driver. It moves this interface's recordings against the others, and nothing else.",
    watch: "The trim is a constant. It is not the phase, which moves every session and is measured by the driver, and it is not the phase reference, which is written beside it by a measurement.",
  },
  "aggregate.device-phase": {
    title: "Phase now",
    what: "What this session's phase measurement came to, while a DAW has the driver open: whether the interface was lined up to its reference, or why not, with what was measured and what was applied, in samples.",
    effect: "Nothing to press. It is measured again at the start of every session.",
    watch: "This is not a trim. A refused measurement means the session ran on the figures the drivers report.",
  },
  "aggregate.device-phase-open": {
    title: "Phase setup",
    what: "Where the driver measures this interface's phase: the digital cable from the callback master, named by the channel it leaves on and the channel it arrives on. Two interfaces start a different whole number of 32 sample steps apart every session, and this is what lets the driver put each session back where the trim was measured.",
  },
  "aggregate.device-phase-summary": {
    title: "Phase setup",
    what: "Whether this interface's phase is set up to be measured, and whether it has a reference to be lined up to yet. A reference comes from one measurement under Line the interfaces up.",
  },
  "aggregate.device-phase-leaves": {
    title: "Leaves the callback master on",
    what: "The callback master's own USB playback channel the measurement goes out on, which is the one routed to the socket the digital cable leaves from.",
    effect: "Saved in the workspace once both channels are chosen. Choosing a different path takes the old reference out, so measure once afterwards. The wheel does not step this menu.",
    watch: "The driver keeps this channel for itself: a DAW no longer sees it.",
  },
  "aggregate.device-phase-arrives": {
    title: "Arrives on",
    what: "This interface's own USB record channel the measurement comes back on, which is the one the socket the digital cable arrives at is routed to.",
    effect: "Saved in the workspace once both channels are chosen. Choosing a different path takes the old reference out, so measure once afterwards. The wheel does not step this menu.",
    watch: "The driver keeps this channel for itself: a DAW no longer sees it.",
  },
  "aggregate.device-phase-clear": {
    title: "Clear",
    what: "Takes this interface's phase setup out, reference and all, so its sessions line up by the figures its driver reports again. Click twice.",
    effect: "Saved in the workspace and written out for the driver. A reference cleared comes back only from another measurement.",
  },
  "aggregate.device-out-trim": { title: "Output trim", what: "Samples added to what this interface's driver says its output latency is, for lining its playback up with the others." },
  "aggregate.device-up": { title: "Move earlier", what: "Moves this interface one place up the list. The order is the order its channels appear to a DAW." },
  "aggregate.device-down": { title: "Move later", what: "Moves this interface one place down the list. The order is the order its channels appear to a DAW." },
  "aggregate.device-remove": { title: "Remove", what: "Takes this interface out of the aggregate. Click twice.", effect: "Nothing on the interface changes. A DAW using the aggregate loses those channels at its next buffer change." },
  "aggregate.match": {
    title: "Match buffer sizes",
    what: "Puts every interface's driver on the same buffer size, which is the one the callback master is on. They will not run together on different sizes.",
    effect: "Click twice. Every program using those drivers, a DAW included, restarts its audio.",
  },
  "aggregate.add-select": {
    title: "Interface to add",
    what: "The audio drivers on this PC that the aggregate does not already open, each named for the device it is where Gazelle can tell, with the driver's own name after it. The wheel does not step this menu.",
  },
  "aggregate.add": { title: "Add", what: "Puts the chosen interface at the end of the aggregate, so its channels come after the others.", effect: "Saved in the workspace and written out for the driver. Nothing is sent to a device." },
  "aggregate.setup": { title: "Setup", what: "The choices that are about the aggregate as a whole rather than about one interface, and where the file the driver reads is written." },
  "aggregate.master": {
    title: "Callback master",
    what: "Which interface drives the DAW's callback. Everything else is lined up against its clock, so it should be the one the others take their clock from over the cable.",
    effect: "Saved in the workspace by the interface's driver, which renaming the device does not change, so a rename never loses it. The wheel does not step this menu.",
  },
  "aggregate.alignment": {
    title: "Alignment",
    what: "Aligned pads every interface so they all line up, at the cost of a little latency. Lowest latency pads nothing, so interfaces of different latencies are offset from each other.",
    effect: "Aligned is what you want unless you are counting samples of latency and can live with the offset.",
  },
  "aggregate.rate": { title: "Sample rate", what: "The rate to put every interface at. Left as it is, the aggregate takes whatever the interfaces are already on.", effect: "Saved in the workspace and written out for the driver." },
  "aggregate.buffer": { title: "Buffer size", what: "The buffer size the aggregate offers a DAW as its preferred one. Left as it is, it offers what the drivers are already on." },
  "aggregate.calibrate": {
    title: "Line the interfaces up",
    what: "Measures how far apart the interfaces are, in samples, instead of leaving you to work it out by comparing waveforms. It plays one click through the aggregate itself and hears where each interface puts it, so what is measured is exactly what the aggregate produces.",
    effect: "It plays a click out of a real output and takes the audio drivers for itself while it runs, so close any DAW that has them open first.",
    watch: "A measurement is only true for the rate and buffer size it was made at. Measure again after changing either.",
  },
  "aggregate.calibrate-direction": {
    title: "Which way round to measure",
    what: "Inputs lines up what the interfaces record: one interface plays the click, and every interface records it. Outputs is the same thing the other way round, with one output on each interface cabled into one interface's inputs.",
    effect: "It decides which trim each interface gets, and which cables you patch. The wheel does not step this menu.",
  },
  "aggregate.calibrate-reference": {
    title: "Reference",
    what: "The one interface every cable has an end on: it plays all the clicks for the input pass, and records them all for the output pass. Everything else is measured against it, so its own reading is zero.",
    effect: "Choose the one with spare channels to hand. The wheel does not step this menu.",
  },
  "aggregate.calibrate-clicks": {
    title: "Clicks",
    what: "How many clicks to play. More of them take longer and give a steadier answer, and they are what the spread in the readings is worked out from.",
  },
  "aggregate.calibrate-level": {
    title: "Level",
    what: "How loud the click is, in dBFS. It comes out of a real output, so keep it modest and turn monitors down before measuring.",
    watch: "Too quiet and the measurement may not find the clicks at all; the reading then says how many it found.",
  },
  "aggregate.calibrate-plays": {
    title: "Plays the click",
    what: "The USB playback channel this interface's click leaves from, named as its channels are named everywhere on this page. Route it to the output socket the cable leaves from.",
    effect: "The cabling below follows what is chosen here, channel by channel.",
  },
  "aggregate.calibrate-records": {
    title: "Records the click",
    what: "The USB record channel the click arrives on, named as its channels are named everywhere on this page. Route the input socket the cable arrives at to it.",
    effect: "The cabling below follows what is chosen here, channel by channel.",
  },
  "aggregate.calibrate-cable": {
    title: "One cable to patch",
    what: "One cable, named by the channels chosen above and the interface each is on: the playback channel it leaves from, and the record channel it arrives at. Patch all of them, then press Measure.",
  },
  "aggregate.calibrate-measure": {
    title: "Measure",
    what: "Plays the clicks and works out how far apart the interfaces are. Click twice.",
    effect: "A click comes out of a real output, and the audio drivers are taken for this measurement while it runs, so a DAW holding them will stop it.",
    watch: "Turn monitors down first. It is quiet, but it is a real signal out of a real output.",
  },
  "aggregate.calibrate-check": {
    title: "Check",
    what: "Plays the same clicks through the same cables, with the session lined up exactly as a DAW's is, and says how far apart a recording would land now. Click twice.",
    effect: "It writes nothing and offers no trims. Like Measure, a click comes out of a real output and the audio drivers are taken while it runs.",
    watch: "Use it after measuring, and whenever you want to know the trims still hold: every session starts somewhere different, and a check shows the driver putting it back.",
  },
  "aggregate.calibrate-stop": { title: "Stop", what: "Stops the measurement that is running and gives the audio drivers back. Nothing is written.", effect: "Nothing measured so far is kept." },
  "aggregate.calibrate-step": { title: "What it is doing", what: "The step the measurement is on, and how far through it is. It is over in a few seconds." },
  "aggregate.calibrate-lag": {
    title: "How far out",
    what: "How far this interface is from the reference, in samples. Late means it records after the reference does, which a positive input trim puts right.",
    watch: "It is only true for the rate and buffer size it was measured at.",
  },
  "aggregate.calibrate-spread": {
    title: "How steady it was",
    what: "How much the clicks disagreed with each other, in samples. A small spread is a reading to trust; a large one means something moved while it measured.",
  },
  "aggregate.calibrate-found": { title: "Clicks found", what: "How many of the clicks played were actually heard on this interface. Fewer than were played means a cable, a routing or a level to look at." },
  "aggregate.calibrate-drift": {
    title: "Drift",
    what: "The clicks moved across the run rather than sitting still, which means the interfaces are not running from one clock.",
    effect: "No trim can put this right: a number that is right now will be wrong in a minute.",
    watch: "Put every interface on the clock that comes down the digital cable between them, then measure again.",
  },
  "aggregate.calibrate-clean": {
    title: "Clean",
    what: "Whether any interface lost a block of audio while the run was going. A lost block moves the very thing being measured, so a run that was not clean is one to run again rather than believe.",
  },
  "aggregate.calibrate-lost": {
    title: "Blocks lost",
    what: "How many blocks this interface's audio dropped or missed while the run was going. Anything but none means the clicks were measured across a fault.",
  },
  "aggregate.calibrate-verdict": {
    title: "Verdict",
    what: "What a check found for this interface: how far from the reference a recording would land now, with the session lined up as a DAW's is. Within a sample reads as lined up.",
    watch: "Out by more than that means the trims no longer hold: measure again, then check.",
  },
  "aggregate.calibrate-phase": {
    title: "The phase in this run",
    what: "What the driver's phase measurement made of this interface at the start of the run. A measurement measures it and applies nothing, on purpose, because it is the reference written with the trim; a check lines it up as a DAW's session would be.",
    watch: "Refused means nothing usable came back on the cable. Check the cable and the routing that carries it.",
  },
  "aggregate.calibrate-phase-figures": { title: "Measured and applied", what: "What the phase measurement came to, and what was added to this interface's input path because of it, in samples. A measurement applies nothing." },
  "aggregate.calibrate-phase-note": { title: "What the driver said", what: "The driver's own sentence about this interface's phase, in the words its log keeps." },
  "aggregate.calibrate-witness": {
    title: "Listened in on",
    what: "An extra input channel the run recorded beside the measurement, and how far from the reference the click landed on it. It is an observation and changes no trim.",
  },
  "aggregate.calibrate-phase-reference": {
    title: "Phase reference",
    what: "The phase measured in this run beside this trim, which is written together with it: every session is lined up by the reference minus its own phase before the trim applies. Not a trim, and not something to type.",
    effect: "Writing the trims writes it too, and takes the old one out when nothing was heard on the cable, so a new trim is never left beside a reference from another session.",
  },
  "aggregate.calibrate-note": { title: "What it made of this interface", what: "The measurement's own sentence about this interface, whether it went well or not." },
  "aggregate.calibrate-not-applied": {
    title: "Not offered",
    what: "Why this trim is not one of the ones the button writes: the reference has nothing to correct against itself, and a reading the measurement does not trust is not worth writing.",
  },
  "aggregate.calibrate-trim-was": { title: "Now", what: "The trim this interface has in its card at the moment, in samples." },
  "aggregate.calibrate-trim-measured": { title: "Measured", what: "What this measurement says the trim should be, in samples." },
  "aggregate.calibrate-trim-now": { title: "Would be", what: "What the trim becomes if these are written into the setup." },
  "aggregate.calibrate-apply": {
    title: "Write these trims into the setup",
    what: "Puts the measured trims into the interfaces' own trim fields, as if they had been typed there, each with the phase reference measured beside it.",
    effect: "Saved in the workspace and written out for the driver. Nothing is sent to a device, and the fields can still be changed by hand afterwards.",
  },
  "aggregate.live": { title: "While a DAW has it open", what: "What the driver itself is reporting: the plan it is running and how each interface is keeping up. It publishes only while a DAW holds it open, so silence here is the ordinary state." },
  "aggregate.plan-master": { title: "Master", what: "The interface driving the callback in the plan the driver is actually running, which may not be the one the setup now names." },
  "aggregate.plan-rate": { title: "Rate", what: "The sample rate the driver is running at." },
  "aggregate.plan-buffer": { title: "Buffer", what: "The buffer size the driver handed the DAW." },
  "aggregate.plan-channels": { title: "Channels", what: "How many channels the DAW actually asked for, which can be fewer than the aggregate offers." },
  "aggregate.plan-alignment": { title: "Alignment", what: "Whether the driver is padding the interfaces to line up, or running each at its own latency." },
  "aggregate.plan-latency": { title: "Latency", what: "The one figure each way the aggregate reports for the whole of itself, in samples." },
  "aggregate.plan-generation": {
    title: "Setup in force",
    what: "The driver is still running an older version of the setup than the one Gazelle last asked for.",
    effect: "While a DAW is streaming the driver takes a change at the next buffer change, so this catches up by itself in a moment.",
  },
  "aggregate.plan-refusal": { title: "Last refused", what: "The last thing the driver would not do, in the same words the DAW was given. It is the line that explains a session that would not start." },
  "aggregate.live-gap": {
    title: "Gap",
    what: "This interface's sample count minus the master's, while both are streaming. In step is zero and is the reading you want.",
    watch: "A gap that keeps growing in one direction is two clocks rather than one: check the cable and every interface's clock source.",
  },
  "aggregate.live-phase": {
    title: "Phase",
    what: "What this session's phase measurement came to for this interface: lined up to its reference, measured with no reference yet, or refused, with what was measured and what was applied, in samples.",
    watch: "Measured with no reference yet means one measurement under Line the interfaces up is all it needs.",
  },
  "aggregate.live-callbacks": { title: "Blocks", what: "How many blocks of audio this interface has handled since the session started." },
  "aggregate.live-dropped": { title: "Dropped", what: "Blocks thrown away because this interface's buffer was full, which is an interface running ahead of the others." },
  "aggregate.live-starved": { title: "Starved", what: "Blocks that were not there when they were wanted, which is what a person hears as a click." },
  "aggregate.events": {
    title: "What happened",
    what: "The driver's own log of things that happened: sessions starting and ending with what they lost, an interface stalling and recovering or losing a block, each session's phase, a setup adopted, and anything refused.",
    effect: "It is kept on disk and only written when something happens, so a session that would not start last night still says why today.",
  },
  "aggregate.event-kind": {
    title: "What kind of line",
    what: "Session started and Session ended open and close a session, and the end says what it lost. Phase measured is what that session's phase measurement came to. Lost a block is the first block a session lost. Stalled, Recovered, Refused, Setup taken up and Reset asked for are what they say.",
  },
  "aggregate.event-gazelle": {
    title: "Gazelle",
    what: "Written during one of Gazelle's own measurements or checks rather than a DAW's session, so it is not something that happened to a recording.",
  },

  // Notices.
  "notices.error": { title: "Error", what: "Something the app tried did not work. It stays until you dismiss it." },
  "notices.warning": { title: "Warning", what: "Something worth knowing, such as the server not finding the devices. It stays until you dismiss it." },
  "notices.info": { title: "Notice", what: "Something the app wants you to know. It stays until you dismiss it." },
  "notices.dismiss": { title: "Dismiss", what: "Closes this notice." },
};
